// Code generated by ent, DO NOT EDIT.

package tree

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark-go/so/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Tree {
	return predicate.Tree(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Tree {
	return predicate.Tree(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Tree {
	return predicate.Tree(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Tree {
	return predicate.Tree(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Tree {
	return predicate.Tree(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Tree {
	return predicate.Tree(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Tree {
	return predicate.Tree(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Tree {
	return predicate.Tree(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Tree {
	return predicate.Tree(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldEQ(FieldUpdateTime, v))
}

// RootID applies equality check predicate on the "root_id" field. It's identical to RootIDEQ.
func RootID(v uuid.UUID) predicate.Tree {
	return predicate.Tree(sql.FieldEQ(FieldRootID, v))
}

// OwnerIdentityPubkey applies equality check predicate on the "owner_identity_pubkey" field. It's identical to OwnerIdentityPubkeyEQ.
func OwnerIdentityPubkey(v []byte) predicate.Tree {
	return predicate.Tree(sql.FieldEQ(FieldOwnerIdentityPubkey, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Tree {
	return predicate.Tree(sql.FieldLTE(FieldUpdateTime, v))
}

// RootIDEQ applies the EQ predicate on the "root_id" field.
func RootIDEQ(v uuid.UUID) predicate.Tree {
	return predicate.Tree(sql.FieldEQ(FieldRootID, v))
}

// RootIDNEQ applies the NEQ predicate on the "root_id" field.
func RootIDNEQ(v uuid.UUID) predicate.Tree {
	return predicate.Tree(sql.FieldNEQ(FieldRootID, v))
}

// RootIDIn applies the In predicate on the "root_id" field.
func RootIDIn(vs ...uuid.UUID) predicate.Tree {
	return predicate.Tree(sql.FieldIn(FieldRootID, vs...))
}

// RootIDNotIn applies the NotIn predicate on the "root_id" field.
func RootIDNotIn(vs ...uuid.UUID) predicate.Tree {
	return predicate.Tree(sql.FieldNotIn(FieldRootID, vs...))
}

// OwnerIdentityPubkeyEQ applies the EQ predicate on the "owner_identity_pubkey" field.
func OwnerIdentityPubkeyEQ(v []byte) predicate.Tree {
	return predicate.Tree(sql.FieldEQ(FieldOwnerIdentityPubkey, v))
}

// OwnerIdentityPubkeyNEQ applies the NEQ predicate on the "owner_identity_pubkey" field.
func OwnerIdentityPubkeyNEQ(v []byte) predicate.Tree {
	return predicate.Tree(sql.FieldNEQ(FieldOwnerIdentityPubkey, v))
}

// OwnerIdentityPubkeyIn applies the In predicate on the "owner_identity_pubkey" field.
func OwnerIdentityPubkeyIn(vs ...[]byte) predicate.Tree {
	return predicate.Tree(sql.FieldIn(FieldOwnerIdentityPubkey, vs...))
}

// OwnerIdentityPubkeyNotIn applies the NotIn predicate on the "owner_identity_pubkey" field.
func OwnerIdentityPubkeyNotIn(vs ...[]byte) predicate.Tree {
	return predicate.Tree(sql.FieldNotIn(FieldOwnerIdentityPubkey, vs...))
}

// OwnerIdentityPubkeyGT applies the GT predicate on the "owner_identity_pubkey" field.
func OwnerIdentityPubkeyGT(v []byte) predicate.Tree {
	return predicate.Tree(sql.FieldGT(FieldOwnerIdentityPubkey, v))
}

// OwnerIdentityPubkeyGTE applies the GTE predicate on the "owner_identity_pubkey" field.
func OwnerIdentityPubkeyGTE(v []byte) predicate.Tree {
	return predicate.Tree(sql.FieldGTE(FieldOwnerIdentityPubkey, v))
}

// OwnerIdentityPubkeyLT applies the LT predicate on the "owner_identity_pubkey" field.
func OwnerIdentityPubkeyLT(v []byte) predicate.Tree {
	return predicate.Tree(sql.FieldLT(FieldOwnerIdentityPubkey, v))
}

// OwnerIdentityPubkeyLTE applies the LTE predicate on the "owner_identity_pubkey" field.
func OwnerIdentityPubkeyLTE(v []byte) predicate.Tree {
	return predicate.Tree(sql.FieldLTE(FieldOwnerIdentityPubkey, v))
}

// HasRoot applies the HasEdge predicate on the "root" edge.
func HasRoot() predicate.Tree {
	return predicate.Tree(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RootTable, RootColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRootWith applies the HasEdge predicate on the "root" edge with a given conditions (other predicates).
func HasRootWith(preds ...predicate.Leaf) predicate.Tree {
	return predicate.Tree(func(s *sql.Selector) {
		step := newRootStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLeaves applies the HasEdge predicate on the "leaves" edge.
func HasLeaves() predicate.Tree {
	return predicate.Tree(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LeavesTable, LeavesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLeavesWith applies the HasEdge predicate on the "leaves" edge with a given conditions (other predicates).
func HasLeavesWith(preds ...predicate.Leaf) predicate.Tree {
	return predicate.Tree(func(s *sql.Selector) {
		step := newLeavesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Tree) predicate.Tree {
	return predicate.Tree(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Tree) predicate.Tree {
	return predicate.Tree(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Tree) predicate.Tree {
	return predicate.Tree(sql.NotPredicates(p))
}
