// Code generated by ent, DO NOT EDIT.

package leafdecomposition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/common/keys"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldEQ(FieldUpdateTime, v))
}

// DelegateSigningPubkey applies equality check predicate on the "delegate_signing_pubkey" field. It's identical to DelegateSigningPubkeyEQ.
func DelegateSigningPubkey(v keys.Public) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldEQ(FieldDelegateSigningPubkey, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldLTE(FieldUpdateTime, v))
}

// DelegateSigningPubkeyEQ applies the EQ predicate on the "delegate_signing_pubkey" field.
func DelegateSigningPubkeyEQ(v keys.Public) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldEQ(FieldDelegateSigningPubkey, v))
}

// DelegateSigningPubkeyNEQ applies the NEQ predicate on the "delegate_signing_pubkey" field.
func DelegateSigningPubkeyNEQ(v keys.Public) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldNEQ(FieldDelegateSigningPubkey, v))
}

// DelegateSigningPubkeyIn applies the In predicate on the "delegate_signing_pubkey" field.
func DelegateSigningPubkeyIn(vs ...keys.Public) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldIn(FieldDelegateSigningPubkey, vs...))
}

// DelegateSigningPubkeyNotIn applies the NotIn predicate on the "delegate_signing_pubkey" field.
func DelegateSigningPubkeyNotIn(vs ...keys.Public) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldNotIn(FieldDelegateSigningPubkey, vs...))
}

// DelegateSigningPubkeyGT applies the GT predicate on the "delegate_signing_pubkey" field.
func DelegateSigningPubkeyGT(v keys.Public) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldGT(FieldDelegateSigningPubkey, v))
}

// DelegateSigningPubkeyGTE applies the GTE predicate on the "delegate_signing_pubkey" field.
func DelegateSigningPubkeyGTE(v keys.Public) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldGTE(FieldDelegateSigningPubkey, v))
}

// DelegateSigningPubkeyLT applies the LT predicate on the "delegate_signing_pubkey" field.
func DelegateSigningPubkeyLT(v keys.Public) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldLT(FieldDelegateSigningPubkey, v))
}

// DelegateSigningPubkeyLTE applies the LTE predicate on the "delegate_signing_pubkey" field.
func DelegateSigningPubkeyLTE(v keys.Public) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.FieldLTE(FieldDelegateSigningPubkey, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v schematype.LeafDecompositionStatus) predicate.LeafDecomposition {
	vc := v
	return predicate.LeafDecomposition(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v schematype.LeafDecompositionStatus) predicate.LeafDecomposition {
	vc := v
	return predicate.LeafDecomposition(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...schematype.LeafDecompositionStatus) predicate.LeafDecomposition {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.LeafDecomposition(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...schematype.LeafDecompositionStatus) predicate.LeafDecomposition {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.LeafDecomposition(sql.FieldNotIn(FieldStatus, v...))
}

// HasTreeNode applies the HasEdge predicate on the "tree_node" edge.
func HasTreeNode() predicate.LeafDecomposition {
	return predicate.LeafDecomposition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TreeNodeTable, TreeNodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTreeNodeWith applies the HasEdge predicate on the "tree_node" edge with a given conditions (other predicates).
func HasTreeNodeWith(preds ...predicate.TreeNode) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(func(s *sql.Selector) {
		step := newTreeNodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSigningKeyshare applies the HasEdge predicate on the "signing_keyshare" edge.
func HasSigningKeyshare() predicate.LeafDecomposition {
	return predicate.LeafDecomposition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, SigningKeyshareTable, SigningKeyshareColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSigningKeyshareWith applies the HasEdge predicate on the "signing_keyshare" edge with a given conditions (other predicates).
func HasSigningKeyshareWith(preds ...predicate.SigningKeyshare) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(func(s *sql.Selector) {
		step := newSigningKeyshareStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDelegationGrant applies the HasEdge predicate on the "delegation_grant" edge.
func HasDelegationGrant() predicate.LeafDecomposition {
	return predicate.LeafDecomposition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DelegationGrantTable, DelegationGrantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDelegationGrantWith applies the HasEdge predicate on the "delegation_grant" edge with a given conditions (other predicates).
func HasDelegationGrantWith(preds ...predicate.DelegationGrant) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(func(s *sql.Selector) {
		step := newDelegationGrantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LeafDecomposition) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LeafDecomposition) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LeafDecomposition) predicate.LeafDecomposition {
	return predicate.LeafDecomposition(sql.NotPredicates(p))
}
