// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/common/btcnetwork"
	"github.com/lightsparkdev/spark/common/keys"
	"github.com/lightsparkdev/spark/so/ent/delegationgrant"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
)

// DelegationGrant is the model entity for the DelegationGrant schema.
type DelegationGrant struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// The time when the entity was created.
	CreateTime time.Time `json:"create_time,omitempty"`
	// The time when the entity was last updated.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Owner's root identity public key. Authorizes grant, spender, and revoke operations; never shared.
	OwnerIdentityPubkey keys.Public `json:"owner_identity_pubkey,omitempty"`
	// Grant lifecycle status (ACTIVE or REVOKED). REVOKED rows are tombstones, never deleted.
	Status schematype.DelegationStatus `json:"status,omitempty"`
	// Bitcoin network this grant applies to.
	Network btcnetwork.Network `json:"network,omitempty"`
	// Wall-clock time after which the grant is no longer valid.
	ExpiryTime time.Time `json:"expiry_time,omitempty"`
	// Whether the delegate path may authorize transfers.
	ScopeTransfer bool `json:"scope_transfer,omitempty"`
	// Whether the delegate path may authorize leaf renewals.
	ScopeRenew bool `json:"scope_renew,omitempty"`
	// Whether the delegate path may authorize offline claims.
	ScopeClaim bool `json:"scope_claim,omitempty"`
	// Flat fee (sats) a delegated settlement must pay the fee collector.
	FeeFlatSats uint64 `json:"fee_flat_sats,omitempty"`
	// Identity public key that receives the flat fee; null when no fee is charged.
	FeeCollectorIdentityPubkey keys.Public `json:"fee_collector_identity_pubkey,omitempty"`
	// Monotonic version; owner-signed re-versions supersede lower versions.
	Version uint64 `json:"version,omitempty"`
	// Owner's ECDSA signature over the grant statement (common.CreateDelegationGrantStatement).
	OwnerSignature []byte `json:"owner_signature,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DelegationGrantQuery when eager-loading is set.
	Edges        DelegationGrantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DelegationGrantEdges holds the relations/edges for other nodes in the graph.
type DelegationGrantEdges struct {
	// Authorized spenders on this grant's delegate path, each independently metered.
	Spenders []*DelegationGrantSpender `json:"spenders,omitempty"`
	// Delegate-path decompositions installed on the owner's leaves under this grant.
	LeafDecompositions []*LeafDecomposition `json:"leaf_decompositions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SpendersOrErr returns the Spenders value or an error if the edge
// was not loaded in eager-loading.
func (e DelegationGrantEdges) SpendersOrErr() ([]*DelegationGrantSpender, error) {
	if e.loadedTypes[0] {
		return e.Spenders, nil
	}
	return nil, &NotLoadedError{edge: "spenders"}
}

// LeafDecompositionsOrErr returns the LeafDecompositions value or an error if the edge
// was not loaded in eager-loading.
func (e DelegationGrantEdges) LeafDecompositionsOrErr() ([]*LeafDecomposition, error) {
	if e.loadedTypes[1] {
		return e.LeafDecompositions, nil
	}
	return nil, &NotLoadedError{edge: "leaf_decompositions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DelegationGrant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case delegationgrant.FieldOwnerSignature:
			values[i] = new([]byte)
		case delegationgrant.FieldNetwork:
			values[i] = new(btcnetwork.Network)
		case delegationgrant.FieldOwnerIdentityPubkey, delegationgrant.FieldFeeCollectorIdentityPubkey:
			values[i] = new(keys.Public)
		case delegationgrant.FieldScopeTransfer, delegationgrant.FieldScopeRenew, delegationgrant.FieldScopeClaim:
			values[i] = new(sql.NullBool)
		case delegationgrant.FieldFeeFlatSats, delegationgrant.FieldVersion:
			values[i] = new(sql.NullInt64)
		case delegationgrant.FieldStatus:
			values[i] = new(sql.NullString)
		case delegationgrant.FieldCreateTime, delegationgrant.FieldUpdateTime, delegationgrant.FieldExpiryTime:
			values[i] = new(sql.NullTime)
		case delegationgrant.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DelegationGrant fields.
func (dg *DelegationGrant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case delegationgrant.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				dg.ID = *value
			}
		case delegationgrant.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				dg.CreateTime = value.Time
			}
		case delegationgrant.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				dg.UpdateTime = value.Time
			}
		case delegationgrant.FieldOwnerIdentityPubkey:
			if value, ok := values[i].(*keys.Public); !ok {
				return fmt.Errorf("unexpected type %T for field owner_identity_pubkey", values[i])
			} else if value != nil {
				dg.OwnerIdentityPubkey = *value
			}
		case delegationgrant.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				dg.Status = schematype.DelegationStatus(value.String)
			}
		case delegationgrant.FieldNetwork:
			if value, ok := values[i].(*btcnetwork.Network); !ok {
				return fmt.Errorf("unexpected type %T for field network", values[i])
			} else if value != nil {
				dg.Network = *value
			}
		case delegationgrant.FieldExpiryTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expiry_time", values[i])
			} else if value.Valid {
				dg.ExpiryTime = value.Time
			}
		case delegationgrant.FieldScopeTransfer:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field scope_transfer", values[i])
			} else if value.Valid {
				dg.ScopeTransfer = value.Bool
			}
		case delegationgrant.FieldScopeRenew:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field scope_renew", values[i])
			} else if value.Valid {
				dg.ScopeRenew = value.Bool
			}
		case delegationgrant.FieldScopeClaim:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field scope_claim", values[i])
			} else if value.Valid {
				dg.ScopeClaim = value.Bool
			}
		case delegationgrant.FieldFeeFlatSats:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fee_flat_sats", values[i])
			} else if value.Valid {
				dg.FeeFlatSats = uint64(value.Int64)
			}
		case delegationgrant.FieldFeeCollectorIdentityPubkey:
			if value, ok := values[i].(*keys.Public); !ok {
				return fmt.Errorf("unexpected type %T for field fee_collector_identity_pubkey", values[i])
			} else if value != nil {
				dg.FeeCollectorIdentityPubkey = *value
			}
		case delegationgrant.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				dg.Version = uint64(value.Int64)
			}
		case delegationgrant.FieldOwnerSignature:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field owner_signature", values[i])
			} else if value != nil {
				dg.OwnerSignature = *value
			}
		default:
			dg.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DelegationGrant.
// This includes values selected through modifiers, order, etc.
func (dg *DelegationGrant) Value(name string) (ent.Value, error) {
	return dg.selectValues.Get(name)
}

// QuerySpenders queries the "spenders" edge of the DelegationGrant entity.
func (dg *DelegationGrant) QuerySpenders() *DelegationGrantSpenderQuery {
	return NewDelegationGrantClient(dg.config).QuerySpenders(dg)
}

// QueryLeafDecompositions queries the "leaf_decompositions" edge of the DelegationGrant entity.
func (dg *DelegationGrant) QueryLeafDecompositions() *LeafDecompositionQuery {
	return NewDelegationGrantClient(dg.config).QueryLeafDecompositions(dg)
}

// Update returns a builder for updating this DelegationGrant.
// Note that you need to call DelegationGrant.Unwrap() before calling this method if this DelegationGrant
// was returned from a transaction, and the transaction was committed or rolled back.
func (dg *DelegationGrant) Update() *DelegationGrantUpdateOne {
	return NewDelegationGrantClient(dg.config).UpdateOne(dg)
}

// Unwrap unwraps the DelegationGrant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (dg *DelegationGrant) Unwrap() *DelegationGrant {
	_tx, ok := dg.config.driver.(*txDriver)
	if !ok {
		panic("ent: DelegationGrant is not a transactional entity")
	}
	dg.config.driver = _tx.drv
	return dg
}

// String implements the fmt.Stringer.
func (dg *DelegationGrant) String() string {
	var builder strings.Builder
	builder.WriteString("DelegationGrant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", dg.ID))
	builder.WriteString("create_time=")
	builder.WriteString(dg.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(dg.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("owner_identity_pubkey=")
	builder.WriteString(fmt.Sprintf("%v", dg.OwnerIdentityPubkey))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", dg.Status))
	builder.WriteString(", ")
	builder.WriteString("network=")
	builder.WriteString(fmt.Sprintf("%v", dg.Network))
	builder.WriteString(", ")
	builder.WriteString("expiry_time=")
	builder.WriteString(dg.ExpiryTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("scope_transfer=")
	builder.WriteString(fmt.Sprintf("%v", dg.ScopeTransfer))
	builder.WriteString(", ")
	builder.WriteString("scope_renew=")
	builder.WriteString(fmt.Sprintf("%v", dg.ScopeRenew))
	builder.WriteString(", ")
	builder.WriteString("scope_claim=")
	builder.WriteString(fmt.Sprintf("%v", dg.ScopeClaim))
	builder.WriteString(", ")
	builder.WriteString("fee_flat_sats=")
	builder.WriteString(fmt.Sprintf("%v", dg.FeeFlatSats))
	builder.WriteString(", ")
	builder.WriteString("fee_collector_identity_pubkey=")
	builder.WriteString(fmt.Sprintf("%v", dg.FeeCollectorIdentityPubkey))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", dg.Version))
	builder.WriteString(", ")
	builder.WriteString("owner_signature=")
	builder.WriteString(fmt.Sprintf("%v", dg.OwnerSignature))
	builder.WriteByte(')')
	return builder.String()
}

// DelegationGrants is a parsable slice of DelegationGrant.
type DelegationGrants []*DelegationGrant
