// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lightsparkdev/spark/so/ent/eventmessage"
	"github.com/lightsparkdev/spark/so/ent/predicate"
)

// EventMessageUpdate is the builder for updating EventMessage entities.
type EventMessageUpdate struct {
	config
	hooks     []Hook
	mutation  *EventMessageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the EventMessageUpdate builder.
func (emu *EventMessageUpdate) Where(ps ...predicate.EventMessage) *EventMessageUpdate {
	emu.mutation.Where(ps...)
	return emu
}

// SetUpdateTime sets the "update_time" field.
func (emu *EventMessageUpdate) SetUpdateTime(t time.Time) *EventMessageUpdate {
	emu.mutation.SetUpdateTime(t)
	return emu
}

// SetChannel sets the "channel" field.
func (emu *EventMessageUpdate) SetChannel(s string) *EventMessageUpdate {
	emu.mutation.SetChannel(s)
	return emu
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (emu *EventMessageUpdate) SetNillableChannel(s *string) *EventMessageUpdate {
	if s != nil {
		emu.SetChannel(*s)
	}
	return emu
}

// SetPayload sets the "payload" field.
func (emu *EventMessageUpdate) SetPayload(s string) *EventMessageUpdate {
	emu.mutation.SetPayload(s)
	return emu
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (emu *EventMessageUpdate) SetNillablePayload(s *string) *EventMessageUpdate {
	if s != nil {
		emu.SetPayload(*s)
	}
	return emu
}

// Mutation returns the EventMessageMutation object of the builder.
func (emu *EventMessageUpdate) Mutation() *EventMessageMutation {
	return emu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (emu *EventMessageUpdate) Save(ctx context.Context) (int, error) {
	emu.defaults()
	return withHooks(ctx, emu.sqlSave, emu.mutation, emu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (emu *EventMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := emu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (emu *EventMessageUpdate) Exec(ctx context.Context) error {
	_, err := emu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (emu *EventMessageUpdate) ExecX(ctx context.Context) {
	if err := emu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (emu *EventMessageUpdate) defaults() {
	if _, ok := emu.mutation.UpdateTime(); !ok {
		v := eventmessage.UpdateDefaultUpdateTime()
		emu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (emu *EventMessageUpdate) check() error {
	if v, ok := emu.mutation.Channel(); ok {
		if err := eventmessage.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "EventMessage.channel": %w`, err)}
		}
	}
	if v, ok := emu.mutation.Payload(); ok {
		if err := eventmessage.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "EventMessage.payload": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (emu *EventMessageUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *EventMessageUpdate {
	emu.modifiers = append(emu.modifiers, modifiers...)
	return emu
}

func (emu *EventMessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := emu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventmessage.Table, eventmessage.Columns, sqlgraph.NewFieldSpec(eventmessage.FieldID, field.TypeUUID))
	if ps := emu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := emu.mutation.UpdateTime(); ok {
		_spec.SetField(eventmessage.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := emu.mutation.Channel(); ok {
		_spec.SetField(eventmessage.FieldChannel, field.TypeString, value)
	}
	if value, ok := emu.mutation.Payload(); ok {
		_spec.SetField(eventmessage.FieldPayload, field.TypeString, value)
	}
	_spec.AddModifiers(emu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, emu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	emu.mutation.done = true
	return n, nil
}

// EventMessageUpdateOne is the builder for updating a single EventMessage entity.
type EventMessageUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *EventMessageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (emuo *EventMessageUpdateOne) SetUpdateTime(t time.Time) *EventMessageUpdateOne {
	emuo.mutation.SetUpdateTime(t)
	return emuo
}

// SetChannel sets the "channel" field.
func (emuo *EventMessageUpdateOne) SetChannel(s string) *EventMessageUpdateOne {
	emuo.mutation.SetChannel(s)
	return emuo
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (emuo *EventMessageUpdateOne) SetNillableChannel(s *string) *EventMessageUpdateOne {
	if s != nil {
		emuo.SetChannel(*s)
	}
	return emuo
}

// SetPayload sets the "payload" field.
func (emuo *EventMessageUpdateOne) SetPayload(s string) *EventMessageUpdateOne {
	emuo.mutation.SetPayload(s)
	return emuo
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (emuo *EventMessageUpdateOne) SetNillablePayload(s *string) *EventMessageUpdateOne {
	if s != nil {
		emuo.SetPayload(*s)
	}
	return emuo
}

// Mutation returns the EventMessageMutation object of the builder.
func (emuo *EventMessageUpdateOne) Mutation() *EventMessageMutation {
	return emuo.mutation
}

// Where appends a list predicates to the EventMessageUpdate builder.
func (emuo *EventMessageUpdateOne) Where(ps ...predicate.EventMessage) *EventMessageUpdateOne {
	emuo.mutation.Where(ps...)
	return emuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (emuo *EventMessageUpdateOne) Select(field string, fields ...string) *EventMessageUpdateOne {
	emuo.fields = append([]string{field}, fields...)
	return emuo
}

// Save executes the query and returns the updated EventMessage entity.
func (emuo *EventMessageUpdateOne) Save(ctx context.Context) (*EventMessage, error) {
	emuo.defaults()
	return withHooks(ctx, emuo.sqlSave, emuo.mutation, emuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (emuo *EventMessageUpdateOne) SaveX(ctx context.Context) *EventMessage {
	node, err := emuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (emuo *EventMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := emuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (emuo *EventMessageUpdateOne) ExecX(ctx context.Context) {
	if err := emuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (emuo *EventMessageUpdateOne) defaults() {
	if _, ok := emuo.mutation.UpdateTime(); !ok {
		v := eventmessage.UpdateDefaultUpdateTime()
		emuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (emuo *EventMessageUpdateOne) check() error {
	if v, ok := emuo.mutation.Channel(); ok {
		if err := eventmessage.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "EventMessage.channel": %w`, err)}
		}
	}
	if v, ok := emuo.mutation.Payload(); ok {
		if err := eventmessage.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "EventMessage.payload": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (emuo *EventMessageUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *EventMessageUpdateOne {
	emuo.modifiers = append(emuo.modifiers, modifiers...)
	return emuo
}

func (emuo *EventMessageUpdateOne) sqlSave(ctx context.Context) (_node *EventMessage, err error) {
	if err := emuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventmessage.Table, eventmessage.Columns, sqlgraph.NewFieldSpec(eventmessage.FieldID, field.TypeUUID))
	id, ok := emuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EventMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := emuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, eventmessage.FieldID)
		for _, f := range fields {
			if !eventmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != eventmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := emuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := emuo.mutation.UpdateTime(); ok {
		_spec.SetField(eventmessage.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := emuo.mutation.Channel(); ok {
		_spec.SetField(eventmessage.FieldChannel, field.TypeString, value)
	}
	if value, ok := emuo.mutation.Payload(); ok {
		_spec.SetField(eventmessage.FieldPayload, field.TypeString, value)
	}
	_spec.AddModifiers(emuo.modifiers...)
	_node = &EventMessage{config: emuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, emuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	emuo.mutation.done = true
	return _node, nil
}
