// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/common/keys"
	"github.com/lightsparkdev/spark/so/ent/delegationgrant"
	"github.com/lightsparkdev/spark/so/ent/leafdecomposition"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
	"github.com/lightsparkdev/spark/so/ent/signingkeyshare"
	"github.com/lightsparkdev/spark/so/ent/treenode"
)

// LeafDecomposition is the model entity for the LeafDecomposition schema.
type LeafDecomposition struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// The time when the entity was created.
	CreateTime time.Time `json:"create_time,omitempty"`
	// The time when the entity was last updated.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// The delegate-path user signing public key registered for this leaf (the second decomposition's user share).
	DelegateSigningPubkey keys.Public `json:"delegate_signing_pubkey,omitempty"`
	// Decomposition lifecycle status. Only ACTIVE may contribute a delegate-path signature; CONSUMED/REVOKED/REVOKE_PENDING are terminal or in-flight-terminal.
	Status schematype.LeafDecompositionStatus `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LeafDecompositionQuery when eager-loading is set.
	Edges                                LeafDecompositionEdges `json:"edges"`
	delegation_grant_leaf_decompositions *uuid.UUID
	leaf_decomposition_tree_node         *uuid.UUID
	leaf_decomposition_signing_keyshare  *uuid.UUID
	selectValues                         sql.SelectValues
}

// LeafDecompositionEdges holds the relations/edges for other nodes in the graph.
type LeafDecompositionEdges struct {
	// The leaf this decomposition is installed on.
	TreeNode *TreeNode `json:"tree_node,omitempty"`
	// The SE2 keyshare completing the delegate path. Cleared when the keyshare is hard-deleted at revoke/consume so the row can tombstone.
	SigningKeyshare *SigningKeyshare `json:"signing_keyshare,omitempty"`
	// The grant under which this decomposition was installed.
	DelegationGrant *DelegationGrant `json:"delegation_grant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TreeNodeOrErr returns the TreeNode value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LeafDecompositionEdges) TreeNodeOrErr() (*TreeNode, error) {
	if e.TreeNode != nil {
		return e.TreeNode, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: treenode.Label}
	}
	return nil, &NotLoadedError{edge: "tree_node"}
}

// SigningKeyshareOrErr returns the SigningKeyshare value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LeafDecompositionEdges) SigningKeyshareOrErr() (*SigningKeyshare, error) {
	if e.SigningKeyshare != nil {
		return e.SigningKeyshare, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: signingkeyshare.Label}
	}
	return nil, &NotLoadedError{edge: "signing_keyshare"}
}

// DelegationGrantOrErr returns the DelegationGrant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LeafDecompositionEdges) DelegationGrantOrErr() (*DelegationGrant, error) {
	if e.DelegationGrant != nil {
		return e.DelegationGrant, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: delegationgrant.Label}
	}
	return nil, &NotLoadedError{edge: "delegation_grant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LeafDecomposition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case leafdecomposition.FieldDelegateSigningPubkey:
			values[i] = new(keys.Public)
		case leafdecomposition.FieldStatus:
			values[i] = new(sql.NullString)
		case leafdecomposition.FieldCreateTime, leafdecomposition.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		case leafdecomposition.FieldID:
			values[i] = new(uuid.UUID)
		case leafdecomposition.ForeignKeys[0]: // delegation_grant_leaf_decompositions
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case leafdecomposition.ForeignKeys[1]: // leaf_decomposition_tree_node
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case leafdecomposition.ForeignKeys[2]: // leaf_decomposition_signing_keyshare
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LeafDecomposition fields.
func (ld *LeafDecomposition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case leafdecomposition.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ld.ID = *value
			}
		case leafdecomposition.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				ld.CreateTime = value.Time
			}
		case leafdecomposition.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				ld.UpdateTime = value.Time
			}
		case leafdecomposition.FieldDelegateSigningPubkey:
			if value, ok := values[i].(*keys.Public); !ok {
				return fmt.Errorf("unexpected type %T for field delegate_signing_pubkey", values[i])
			} else if value != nil {
				ld.DelegateSigningPubkey = *value
			}
		case leafdecomposition.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ld.Status = schematype.LeafDecompositionStatus(value.String)
			}
		case leafdecomposition.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field delegation_grant_leaf_decompositions", values[i])
			} else if value.Valid {
				ld.delegation_grant_leaf_decompositions = new(uuid.UUID)
				*ld.delegation_grant_leaf_decompositions = *value.S.(*uuid.UUID)
			}
		case leafdecomposition.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field leaf_decomposition_tree_node", values[i])
			} else if value.Valid {
				ld.leaf_decomposition_tree_node = new(uuid.UUID)
				*ld.leaf_decomposition_tree_node = *value.S.(*uuid.UUID)
			}
		case leafdecomposition.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field leaf_decomposition_signing_keyshare", values[i])
			} else if value.Valid {
				ld.leaf_decomposition_signing_keyshare = new(uuid.UUID)
				*ld.leaf_decomposition_signing_keyshare = *value.S.(*uuid.UUID)
			}
		default:
			ld.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LeafDecomposition.
// This includes values selected through modifiers, order, etc.
func (ld *LeafDecomposition) Value(name string) (ent.Value, error) {
	return ld.selectValues.Get(name)
}

// QueryTreeNode queries the "tree_node" edge of the LeafDecomposition entity.
func (ld *LeafDecomposition) QueryTreeNode() *TreeNodeQuery {
	return NewLeafDecompositionClient(ld.config).QueryTreeNode(ld)
}

// QuerySigningKeyshare queries the "signing_keyshare" edge of the LeafDecomposition entity.
func (ld *LeafDecomposition) QuerySigningKeyshare() *SigningKeyshareQuery {
	return NewLeafDecompositionClient(ld.config).QuerySigningKeyshare(ld)
}

// QueryDelegationGrant queries the "delegation_grant" edge of the LeafDecomposition entity.
func (ld *LeafDecomposition) QueryDelegationGrant() *DelegationGrantQuery {
	return NewLeafDecompositionClient(ld.config).QueryDelegationGrant(ld)
}

// Update returns a builder for updating this LeafDecomposition.
// Note that you need to call LeafDecomposition.Unwrap() before calling this method if this LeafDecomposition
// was returned from a transaction, and the transaction was committed or rolled back.
func (ld *LeafDecomposition) Update() *LeafDecompositionUpdateOne {
	return NewLeafDecompositionClient(ld.config).UpdateOne(ld)
}

// Unwrap unwraps the LeafDecomposition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ld *LeafDecomposition) Unwrap() *LeafDecomposition {
	_tx, ok := ld.config.driver.(*txDriver)
	if !ok {
		panic("ent: LeafDecomposition is not a transactional entity")
	}
	ld.config.driver = _tx.drv
	return ld
}

// String implements the fmt.Stringer.
func (ld *LeafDecomposition) String() string {
	var builder strings.Builder
	builder.WriteString("LeafDecomposition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ld.ID))
	builder.WriteString("create_time=")
	builder.WriteString(ld.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(ld.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("delegate_signing_pubkey=")
	builder.WriteString(fmt.Sprintf("%v", ld.DelegateSigningPubkey))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", ld.Status))
	builder.WriteByte(')')
	return builder.String()
}

// LeafDecompositions is a parsable slice of LeafDecomposition.
type LeafDecompositions []*LeafDecomposition
