// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/common/keys/jwt"
	"github.com/lightsparkdev/spark/so/ent/partner"
	"github.com/lightsparkdev/spark/so/ent/partnerkey"
	"github.com/lightsparkdev/spark/so/ent/predicate"
)

// PartnerKeyUpdate is the builder for updating PartnerKey entities.
type PartnerKeyUpdate struct {
	config
	hooks     []Hook
	mutation  *PartnerKeyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PartnerKeyUpdate builder.
func (pku *PartnerKeyUpdate) Where(ps ...predicate.PartnerKey) *PartnerKeyUpdate {
	pku.mutation.Where(ps...)
	return pku
}

// SetUpdateTime sets the "update_time" field.
func (pku *PartnerKeyUpdate) SetUpdateTime(t time.Time) *PartnerKeyUpdate {
	pku.mutation.SetUpdateTime(t)
	return pku
}

// SetPartnerID sets the "partner_id" field.
func (pku *PartnerKeyUpdate) SetPartnerID(s string) *PartnerKeyUpdate {
	pku.mutation.SetPartnerID(s)
	return pku
}

// SetNillablePartnerID sets the "partner_id" field if the given value is not nil.
func (pku *PartnerKeyUpdate) SetNillablePartnerID(s *string) *PartnerKeyUpdate {
	if s != nil {
		pku.SetPartnerID(*s)
	}
	return pku
}

// SetPartnerName sets the "partner_name" field.
func (pku *PartnerKeyUpdate) SetPartnerName(s string) *PartnerKeyUpdate {
	pku.mutation.SetPartnerName(s)
	return pku
}

// SetNillablePartnerName sets the "partner_name" field if the given value is not nil.
func (pku *PartnerKeyUpdate) SetNillablePartnerName(s *string) *PartnerKeyUpdate {
	if s != nil {
		pku.SetPartnerName(*s)
	}
	return pku
}

// SetJwtPublicKey sets the "jwt_public_key" field.
func (pku *PartnerKeyUpdate) SetJwtPublicKey(j jwt.Public) *PartnerKeyUpdate {
	pku.mutation.SetJwtPublicKey(j)
	return pku
}

// SetNillableJwtPublicKey sets the "jwt_public_key" field if the given value is not nil.
func (pku *PartnerKeyUpdate) SetNillableJwtPublicKey(j *jwt.Public) *PartnerKeyUpdate {
	if j != nil {
		pku.SetJwtPublicKey(*j)
	}
	return pku
}

// SetBasicAuthSecretHash sets the "basic_auth_secret_hash" field.
func (pku *PartnerKeyUpdate) SetBasicAuthSecretHash(s string) *PartnerKeyUpdate {
	pku.mutation.SetBasicAuthSecretHash(s)
	return pku
}

// SetNillableBasicAuthSecretHash sets the "basic_auth_secret_hash" field if the given value is not nil.
func (pku *PartnerKeyUpdate) SetNillableBasicAuthSecretHash(s *string) *PartnerKeyUpdate {
	if s != nil {
		pku.SetBasicAuthSecretHash(*s)
	}
	return pku
}

// ClearBasicAuthSecretHash clears the value of the "basic_auth_secret_hash" field.
func (pku *PartnerKeyUpdate) ClearBasicAuthSecretHash() *PartnerKeyUpdate {
	pku.mutation.ClearBasicAuthSecretHash()
	return pku
}

// AddPartnerIDs adds the "partners" edge to the Partner entity by IDs.
func (pku *PartnerKeyUpdate) AddPartnerIDs(ids ...uuid.UUID) *PartnerKeyUpdate {
	pku.mutation.AddPartnerIDs(ids...)
	return pku
}

// AddPartners adds the "partners" edges to the Partner entity.
func (pku *PartnerKeyUpdate) AddPartners(p ...*Partner) *PartnerKeyUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pku.AddPartnerIDs(ids...)
}

// Mutation returns the PartnerKeyMutation object of the builder.
func (pku *PartnerKeyUpdate) Mutation() *PartnerKeyMutation {
	return pku.mutation
}

// ClearPartners clears all "partners" edges to the Partner entity.
func (pku *PartnerKeyUpdate) ClearPartners() *PartnerKeyUpdate {
	pku.mutation.ClearPartners()
	return pku
}

// RemovePartnerIDs removes the "partners" edge to Partner entities by IDs.
func (pku *PartnerKeyUpdate) RemovePartnerIDs(ids ...uuid.UUID) *PartnerKeyUpdate {
	pku.mutation.RemovePartnerIDs(ids...)
	return pku
}

// RemovePartners removes "partners" edges to Partner entities.
func (pku *PartnerKeyUpdate) RemovePartners(p ...*Partner) *PartnerKeyUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pku.RemovePartnerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pku *PartnerKeyUpdate) Save(ctx context.Context) (int, error) {
	pku.defaults()
	return withHooks(ctx, pku.sqlSave, pku.mutation, pku.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pku *PartnerKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := pku.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pku *PartnerKeyUpdate) Exec(ctx context.Context) error {
	_, err := pku.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pku *PartnerKeyUpdate) ExecX(ctx context.Context) {
	if err := pku.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pku *PartnerKeyUpdate) defaults() {
	if _, ok := pku.mutation.UpdateTime(); !ok {
		v := partnerkey.UpdateDefaultUpdateTime()
		pku.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pku *PartnerKeyUpdate) check() error {
	if v, ok := pku.mutation.PartnerID(); ok {
		if err := partnerkey.PartnerIDValidator(v); err != nil {
			return &ValidationError{Name: "partner_id", err: fmt.Errorf(`ent: validator failed for field "PartnerKey.partner_id": %w`, err)}
		}
	}
	if v, ok := pku.mutation.PartnerName(); ok {
		if err := partnerkey.PartnerNameValidator(v); err != nil {
			return &ValidationError{Name: "partner_name", err: fmt.Errorf(`ent: validator failed for field "PartnerKey.partner_name": %w`, err)}
		}
	}
	if v, ok := pku.mutation.BasicAuthSecretHash(); ok {
		if err := partnerkey.BasicAuthSecretHashValidator(v); err != nil {
			return &ValidationError{Name: "basic_auth_secret_hash", err: fmt.Errorf(`ent: validator failed for field "PartnerKey.basic_auth_secret_hash": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (pku *PartnerKeyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PartnerKeyUpdate {
	pku.modifiers = append(pku.modifiers, modifiers...)
	return pku
}

func (pku *PartnerKeyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pku.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(partnerkey.Table, partnerkey.Columns, sqlgraph.NewFieldSpec(partnerkey.FieldID, field.TypeUUID))
	if ps := pku.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pku.mutation.UpdateTime(); ok {
		_spec.SetField(partnerkey.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := pku.mutation.PartnerID(); ok {
		_spec.SetField(partnerkey.FieldPartnerID, field.TypeString, value)
	}
	if value, ok := pku.mutation.PartnerName(); ok {
		_spec.SetField(partnerkey.FieldPartnerName, field.TypeString, value)
	}
	if value, ok := pku.mutation.JwtPublicKey(); ok {
		_spec.SetField(partnerkey.FieldJwtPublicKey, field.TypeBytes, value)
	}
	if value, ok := pku.mutation.BasicAuthSecretHash(); ok {
		_spec.SetField(partnerkey.FieldBasicAuthSecretHash, field.TypeString, value)
	}
	if pku.mutation.BasicAuthSecretHashCleared() {
		_spec.ClearField(partnerkey.FieldBasicAuthSecretHash, field.TypeString)
	}
	if pku.mutation.PartnersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   partnerkey.PartnersTable,
			Columns: []string{partnerkey.PartnersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pku.mutation.RemovedPartnersIDs(); len(nodes) > 0 && !pku.mutation.PartnersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   partnerkey.PartnersTable,
			Columns: []string{partnerkey.PartnersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pku.mutation.PartnersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   partnerkey.PartnersTable,
			Columns: []string{partnerkey.PartnersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(pku.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, pku.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{partnerkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pku.mutation.done = true
	return n, nil
}

// PartnerKeyUpdateOne is the builder for updating a single PartnerKey entity.
type PartnerKeyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PartnerKeyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (pkuo *PartnerKeyUpdateOne) SetUpdateTime(t time.Time) *PartnerKeyUpdateOne {
	pkuo.mutation.SetUpdateTime(t)
	return pkuo
}

// SetPartnerID sets the "partner_id" field.
func (pkuo *PartnerKeyUpdateOne) SetPartnerID(s string) *PartnerKeyUpdateOne {
	pkuo.mutation.SetPartnerID(s)
	return pkuo
}

// SetNillablePartnerID sets the "partner_id" field if the given value is not nil.
func (pkuo *PartnerKeyUpdateOne) SetNillablePartnerID(s *string) *PartnerKeyUpdateOne {
	if s != nil {
		pkuo.SetPartnerID(*s)
	}
	return pkuo
}

// SetPartnerName sets the "partner_name" field.
func (pkuo *PartnerKeyUpdateOne) SetPartnerName(s string) *PartnerKeyUpdateOne {
	pkuo.mutation.SetPartnerName(s)
	return pkuo
}

// SetNillablePartnerName sets the "partner_name" field if the given value is not nil.
func (pkuo *PartnerKeyUpdateOne) SetNillablePartnerName(s *string) *PartnerKeyUpdateOne {
	if s != nil {
		pkuo.SetPartnerName(*s)
	}
	return pkuo
}

// SetJwtPublicKey sets the "jwt_public_key" field.
func (pkuo *PartnerKeyUpdateOne) SetJwtPublicKey(j jwt.Public) *PartnerKeyUpdateOne {
	pkuo.mutation.SetJwtPublicKey(j)
	return pkuo
}

// SetNillableJwtPublicKey sets the "jwt_public_key" field if the given value is not nil.
func (pkuo *PartnerKeyUpdateOne) SetNillableJwtPublicKey(j *jwt.Public) *PartnerKeyUpdateOne {
	if j != nil {
		pkuo.SetJwtPublicKey(*j)
	}
	return pkuo
}

// SetBasicAuthSecretHash sets the "basic_auth_secret_hash" field.
func (pkuo *PartnerKeyUpdateOne) SetBasicAuthSecretHash(s string) *PartnerKeyUpdateOne {
	pkuo.mutation.SetBasicAuthSecretHash(s)
	return pkuo
}

// SetNillableBasicAuthSecretHash sets the "basic_auth_secret_hash" field if the given value is not nil.
func (pkuo *PartnerKeyUpdateOne) SetNillableBasicAuthSecretHash(s *string) *PartnerKeyUpdateOne {
	if s != nil {
		pkuo.SetBasicAuthSecretHash(*s)
	}
	return pkuo
}

// ClearBasicAuthSecretHash clears the value of the "basic_auth_secret_hash" field.
func (pkuo *PartnerKeyUpdateOne) ClearBasicAuthSecretHash() *PartnerKeyUpdateOne {
	pkuo.mutation.ClearBasicAuthSecretHash()
	return pkuo
}

// AddPartnerIDs adds the "partners" edge to the Partner entity by IDs.
func (pkuo *PartnerKeyUpdateOne) AddPartnerIDs(ids ...uuid.UUID) *PartnerKeyUpdateOne {
	pkuo.mutation.AddPartnerIDs(ids...)
	return pkuo
}

// AddPartners adds the "partners" edges to the Partner entity.
func (pkuo *PartnerKeyUpdateOne) AddPartners(p ...*Partner) *PartnerKeyUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pkuo.AddPartnerIDs(ids...)
}

// Mutation returns the PartnerKeyMutation object of the builder.
func (pkuo *PartnerKeyUpdateOne) Mutation() *PartnerKeyMutation {
	return pkuo.mutation
}

// ClearPartners clears all "partners" edges to the Partner entity.
func (pkuo *PartnerKeyUpdateOne) ClearPartners() *PartnerKeyUpdateOne {
	pkuo.mutation.ClearPartners()
	return pkuo
}

// RemovePartnerIDs removes the "partners" edge to Partner entities by IDs.
func (pkuo *PartnerKeyUpdateOne) RemovePartnerIDs(ids ...uuid.UUID) *PartnerKeyUpdateOne {
	pkuo.mutation.RemovePartnerIDs(ids...)
	return pkuo
}

// RemovePartners removes "partners" edges to Partner entities.
func (pkuo *PartnerKeyUpdateOne) RemovePartners(p ...*Partner) *PartnerKeyUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pkuo.RemovePartnerIDs(ids...)
}

// Where appends a list predicates to the PartnerKeyUpdate builder.
func (pkuo *PartnerKeyUpdateOne) Where(ps ...predicate.PartnerKey) *PartnerKeyUpdateOne {
	pkuo.mutation.Where(ps...)
	return pkuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pkuo *PartnerKeyUpdateOne) Select(field string, fields ...string) *PartnerKeyUpdateOne {
	pkuo.fields = append([]string{field}, fields...)
	return pkuo
}

// Save executes the query and returns the updated PartnerKey entity.
func (pkuo *PartnerKeyUpdateOne) Save(ctx context.Context) (*PartnerKey, error) {
	pkuo.defaults()
	return withHooks(ctx, pkuo.sqlSave, pkuo.mutation, pkuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pkuo *PartnerKeyUpdateOne) SaveX(ctx context.Context) *PartnerKey {
	node, err := pkuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pkuo *PartnerKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := pkuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pkuo *PartnerKeyUpdateOne) ExecX(ctx context.Context) {
	if err := pkuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pkuo *PartnerKeyUpdateOne) defaults() {
	if _, ok := pkuo.mutation.UpdateTime(); !ok {
		v := partnerkey.UpdateDefaultUpdateTime()
		pkuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pkuo *PartnerKeyUpdateOne) check() error {
	if v, ok := pkuo.mutation.PartnerID(); ok {
		if err := partnerkey.PartnerIDValidator(v); err != nil {
			return &ValidationError{Name: "partner_id", err: fmt.Errorf(`ent: validator failed for field "PartnerKey.partner_id": %w`, err)}
		}
	}
	if v, ok := pkuo.mutation.PartnerName(); ok {
		if err := partnerkey.PartnerNameValidator(v); err != nil {
			return &ValidationError{Name: "partner_name", err: fmt.Errorf(`ent: validator failed for field "PartnerKey.partner_name": %w`, err)}
		}
	}
	if v, ok := pkuo.mutation.BasicAuthSecretHash(); ok {
		if err := partnerkey.BasicAuthSecretHashValidator(v); err != nil {
			return &ValidationError{Name: "basic_auth_secret_hash", err: fmt.Errorf(`ent: validator failed for field "PartnerKey.basic_auth_secret_hash": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (pkuo *PartnerKeyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PartnerKeyUpdateOne {
	pkuo.modifiers = append(pkuo.modifiers, modifiers...)
	return pkuo
}

func (pkuo *PartnerKeyUpdateOne) sqlSave(ctx context.Context) (_node *PartnerKey, err error) {
	if err := pkuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(partnerkey.Table, partnerkey.Columns, sqlgraph.NewFieldSpec(partnerkey.FieldID, field.TypeUUID))
	id, ok := pkuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PartnerKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pkuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, partnerkey.FieldID)
		for _, f := range fields {
			if !partnerkey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != partnerkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pkuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pkuo.mutation.UpdateTime(); ok {
		_spec.SetField(partnerkey.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := pkuo.mutation.PartnerID(); ok {
		_spec.SetField(partnerkey.FieldPartnerID, field.TypeString, value)
	}
	if value, ok := pkuo.mutation.PartnerName(); ok {
		_spec.SetField(partnerkey.FieldPartnerName, field.TypeString, value)
	}
	if value, ok := pkuo.mutation.JwtPublicKey(); ok {
		_spec.SetField(partnerkey.FieldJwtPublicKey, field.TypeBytes, value)
	}
	if value, ok := pkuo.mutation.BasicAuthSecretHash(); ok {
		_spec.SetField(partnerkey.FieldBasicAuthSecretHash, field.TypeString, value)
	}
	if pkuo.mutation.BasicAuthSecretHashCleared() {
		_spec.ClearField(partnerkey.FieldBasicAuthSecretHash, field.TypeString)
	}
	if pkuo.mutation.PartnersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   partnerkey.PartnersTable,
			Columns: []string{partnerkey.PartnersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pkuo.mutation.RemovedPartnersIDs(); len(nodes) > 0 && !pkuo.mutation.PartnersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   partnerkey.PartnersTable,
			Columns: []string{partnerkey.PartnersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pkuo.mutation.PartnersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   partnerkey.PartnersTable,
			Columns: []string{partnerkey.PartnersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(partner.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(pkuo.modifiers...)
	_node = &PartnerKey{config: pkuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pkuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{partnerkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pkuo.mutation.done = true
	return _node, nil
}
