// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/partner"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/preimageshare"
	"github.com/lightsparkdev/spark/so/ent/preimagesharepartner"
)

// PreimageSharePartnerQuery is the builder for querying PreimageSharePartner entities.
type PreimageSharePartnerQuery struct {
	config
	ctx               *QueryContext
	order             []preimagesharepartner.OrderOption
	inters            []Interceptor
	predicates        []predicate.PreimageSharePartner
	withPartner       *PartnerQuery
	withPreimageShare *PreimageShareQuery
	withFKs           bool
	modifiers         []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PreimageSharePartnerQuery builder.
func (pspq *PreimageSharePartnerQuery) Where(ps ...predicate.PreimageSharePartner) *PreimageSharePartnerQuery {
	pspq.predicates = append(pspq.predicates, ps...)
	return pspq
}

// Limit the number of records to be returned by this query.
func (pspq *PreimageSharePartnerQuery) Limit(limit int) *PreimageSharePartnerQuery {
	pspq.ctx.Limit = &limit
	return pspq
}

// Offset to start from.
func (pspq *PreimageSharePartnerQuery) Offset(offset int) *PreimageSharePartnerQuery {
	pspq.ctx.Offset = &offset
	return pspq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pspq *PreimageSharePartnerQuery) Unique(unique bool) *PreimageSharePartnerQuery {
	pspq.ctx.Unique = &unique
	return pspq
}

// Order specifies how the records should be ordered.
func (pspq *PreimageSharePartnerQuery) Order(o ...preimagesharepartner.OrderOption) *PreimageSharePartnerQuery {
	pspq.order = append(pspq.order, o...)
	return pspq
}

// QueryPartner chains the current query on the "partner" edge.
func (pspq *PreimageSharePartnerQuery) QueryPartner() *PartnerQuery {
	query := (&PartnerClient{config: pspq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pspq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pspq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(preimagesharepartner.Table, preimagesharepartner.FieldID, selector),
			sqlgraph.To(partner.Table, partner.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, preimagesharepartner.PartnerTable, preimagesharepartner.PartnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(pspq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPreimageShare chains the current query on the "preimage_share" edge.
func (pspq *PreimageSharePartnerQuery) QueryPreimageShare() *PreimageShareQuery {
	query := (&PreimageShareClient{config: pspq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pspq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pspq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(preimagesharepartner.Table, preimagesharepartner.FieldID, selector),
			sqlgraph.To(preimageshare.Table, preimageshare.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, preimagesharepartner.PreimageShareTable, preimagesharepartner.PreimageShareColumn),
		)
		fromU = sqlgraph.SetNeighbors(pspq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PreimageSharePartner entity from the query.
// Returns a *NotFoundError when no PreimageSharePartner was found.
func (pspq *PreimageSharePartnerQuery) First(ctx context.Context) (*PreimageSharePartner, error) {
	nodes, err := pspq.Limit(1).All(setContextOp(ctx, pspq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{preimagesharepartner.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pspq *PreimageSharePartnerQuery) FirstX(ctx context.Context) *PreimageSharePartner {
	node, err := pspq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PreimageSharePartner ID from the query.
// Returns a *NotFoundError when no PreimageSharePartner ID was found.
func (pspq *PreimageSharePartnerQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pspq.Limit(1).IDs(setContextOp(ctx, pspq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{preimagesharepartner.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pspq *PreimageSharePartnerQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := pspq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PreimageSharePartner entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PreimageSharePartner entity is found.
// Returns a *NotFoundError when no PreimageSharePartner entities are found.
func (pspq *PreimageSharePartnerQuery) Only(ctx context.Context) (*PreimageSharePartner, error) {
	nodes, err := pspq.Limit(2).All(setContextOp(ctx, pspq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{preimagesharepartner.Label}
	default:
		return nil, &NotSingularError{preimagesharepartner.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pspq *PreimageSharePartnerQuery) OnlyX(ctx context.Context) *PreimageSharePartner {
	node, err := pspq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PreimageSharePartner ID in the query.
// Returns a *NotSingularError when more than one PreimageSharePartner ID is found.
// Returns a *NotFoundError when no entities are found.
func (pspq *PreimageSharePartnerQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pspq.Limit(2).IDs(setContextOp(ctx, pspq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{preimagesharepartner.Label}
	default:
		err = &NotSingularError{preimagesharepartner.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pspq *PreimageSharePartnerQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := pspq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PreimageSharePartners.
func (pspq *PreimageSharePartnerQuery) All(ctx context.Context) ([]*PreimageSharePartner, error) {
	ctx = setContextOp(ctx, pspq.ctx, ent.OpQueryAll)
	if err := pspq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PreimageSharePartner, *PreimageSharePartnerQuery]()
	return withInterceptors[[]*PreimageSharePartner](ctx, pspq, qr, pspq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pspq *PreimageSharePartnerQuery) AllX(ctx context.Context) []*PreimageSharePartner {
	nodes, err := pspq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PreimageSharePartner IDs.
func (pspq *PreimageSharePartnerQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if pspq.ctx.Unique == nil && pspq.path != nil {
		pspq.Unique(true)
	}
	ctx = setContextOp(ctx, pspq.ctx, ent.OpQueryIDs)
	if err = pspq.Select(preimagesharepartner.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pspq *PreimageSharePartnerQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := pspq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pspq *PreimageSharePartnerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pspq.ctx, ent.OpQueryCount)
	if err := pspq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pspq, querierCount[*PreimageSharePartnerQuery](), pspq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pspq *PreimageSharePartnerQuery) CountX(ctx context.Context) int {
	count, err := pspq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pspq *PreimageSharePartnerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pspq.ctx, ent.OpQueryExist)
	switch _, err := pspq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pspq *PreimageSharePartnerQuery) ExistX(ctx context.Context) bool {
	exist, err := pspq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PreimageSharePartnerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pspq *PreimageSharePartnerQuery) Clone() *PreimageSharePartnerQuery {
	if pspq == nil {
		return nil
	}
	return &PreimageSharePartnerQuery{
		config:            pspq.config,
		ctx:               pspq.ctx.Clone(),
		order:             append([]preimagesharepartner.OrderOption{}, pspq.order...),
		inters:            append([]Interceptor{}, pspq.inters...),
		predicates:        append([]predicate.PreimageSharePartner{}, pspq.predicates...),
		withPartner:       pspq.withPartner.Clone(),
		withPreimageShare: pspq.withPreimageShare.Clone(),
		// clone intermediate query.
		sql:       pspq.sql.Clone(),
		path:      pspq.path,
		modifiers: append([]func(*sql.Selector){}, pspq.modifiers...),
	}
}

// WithPartner tells the query-builder to eager-load the nodes that are connected to
// the "partner" edge. The optional arguments are used to configure the query builder of the edge.
func (pspq *PreimageSharePartnerQuery) WithPartner(opts ...func(*PartnerQuery)) *PreimageSharePartnerQuery {
	query := (&PartnerClient{config: pspq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pspq.withPartner = query
	return pspq
}

// WithPreimageShare tells the query-builder to eager-load the nodes that are connected to
// the "preimage_share" edge. The optional arguments are used to configure the query builder of the edge.
func (pspq *PreimageSharePartnerQuery) WithPreimageShare(opts ...func(*PreimageShareQuery)) *PreimageSharePartnerQuery {
	query := (&PreimageShareClient{config: pspq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	pspq.withPreimageShare = query
	return pspq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PreimageSharePartner.Query().
//		GroupBy(preimagesharepartner.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pspq *PreimageSharePartnerQuery) GroupBy(field string, fields ...string) *PreimageSharePartnerGroupBy {
	pspq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PreimageSharePartnerGroupBy{build: pspq}
	grbuild.flds = &pspq.ctx.Fields
	grbuild.label = preimagesharepartner.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.PreimageSharePartner.Query().
//		Select(preimagesharepartner.FieldCreateTime).
//		Scan(ctx, &v)
func (pspq *PreimageSharePartnerQuery) Select(fields ...string) *PreimageSharePartnerSelect {
	pspq.ctx.Fields = append(pspq.ctx.Fields, fields...)
	sbuild := &PreimageSharePartnerSelect{PreimageSharePartnerQuery: pspq}
	sbuild.label = preimagesharepartner.Label
	sbuild.flds, sbuild.scan = &pspq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PreimageSharePartnerSelect configured with the given aggregations.
func (pspq *PreimageSharePartnerQuery) Aggregate(fns ...AggregateFunc) *PreimageSharePartnerSelect {
	return pspq.Select().Aggregate(fns...)
}

func (pspq *PreimageSharePartnerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pspq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pspq); err != nil {
				return err
			}
		}
	}
	for _, f := range pspq.ctx.Fields {
		if !preimagesharepartner.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pspq.path != nil {
		prev, err := pspq.path(ctx)
		if err != nil {
			return err
		}
		pspq.sql = prev
	}
	return nil
}

func (pspq *PreimageSharePartnerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PreimageSharePartner, error) {
	var (
		nodes       = []*PreimageSharePartner{}
		withFKs     = pspq.withFKs
		_spec       = pspq.querySpec()
		loadedTypes = [2]bool{
			pspq.withPartner != nil,
			pspq.withPreimageShare != nil,
		}
	)
	if pspq.withPartner != nil || pspq.withPreimageShare != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, preimagesharepartner.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PreimageSharePartner).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PreimageSharePartner{config: pspq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(pspq.modifiers) > 0 {
		_spec.Modifiers = pspq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pspq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pspq.withPartner; query != nil {
		if err := pspq.loadPartner(ctx, query, nodes, nil,
			func(n *PreimageSharePartner, e *Partner) { n.Edges.Partner = e }); err != nil {
			return nil, err
		}
	}
	if query := pspq.withPreimageShare; query != nil {
		if err := pspq.loadPreimageShare(ctx, query, nodes, nil,
			func(n *PreimageSharePartner, e *PreimageShare) { n.Edges.PreimageShare = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pspq *PreimageSharePartnerQuery) loadPartner(ctx context.Context, query *PartnerQuery, nodes []*PreimageSharePartner, init func(*PreimageSharePartner), assign func(*PreimageSharePartner, *Partner)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PreimageSharePartner)
	for i := range nodes {
		if nodes[i].preimage_share_partner_partner == nil {
			continue
		}
		fk := *nodes[i].preimage_share_partner_partner
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(partner.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "preimage_share_partner_partner" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (pspq *PreimageSharePartnerQuery) loadPreimageShare(ctx context.Context, query *PreimageShareQuery, nodes []*PreimageSharePartner, init func(*PreimageSharePartner), assign func(*PreimageSharePartner, *PreimageShare)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PreimageSharePartner)
	for i := range nodes {
		if nodes[i].preimage_share_partner_preimage_share == nil {
			continue
		}
		fk := *nodes[i].preimage_share_partner_preimage_share
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(preimageshare.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "preimage_share_partner_preimage_share" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (pspq *PreimageSharePartnerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pspq.querySpec()
	if len(pspq.modifiers) > 0 {
		_spec.Modifiers = pspq.modifiers
	}
	_spec.Node.Columns = pspq.ctx.Fields
	if len(pspq.ctx.Fields) > 0 {
		_spec.Unique = pspq.ctx.Unique != nil && *pspq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pspq.driver, _spec)
}

func (pspq *PreimageSharePartnerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(preimagesharepartner.Table, preimagesharepartner.Columns, sqlgraph.NewFieldSpec(preimagesharepartner.FieldID, field.TypeUUID))
	_spec.From = pspq.sql
	if unique := pspq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pspq.path != nil {
		_spec.Unique = true
	}
	if fields := pspq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, preimagesharepartner.FieldID)
		for i := range fields {
			if fields[i] != preimagesharepartner.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pspq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pspq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pspq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pspq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pspq *PreimageSharePartnerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pspq.driver.Dialect())
	t1 := builder.Table(preimagesharepartner.Table)
	columns := pspq.ctx.Fields
	if len(columns) == 0 {
		columns = preimagesharepartner.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pspq.sql != nil {
		selector = pspq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pspq.ctx.Unique != nil && *pspq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range pspq.modifiers {
		m(selector)
	}
	for _, p := range pspq.predicates {
		p(selector)
	}
	for _, p := range pspq.order {
		p(selector)
	}
	if offset := pspq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pspq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (pspq *PreimageSharePartnerQuery) ForUpdate(opts ...sql.LockOption) *PreimageSharePartnerQuery {
	if pspq.driver.Dialect() == dialect.Postgres {
		pspq.Unique(false)
	}
	pspq.modifiers = append(pspq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return pspq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (pspq *PreimageSharePartnerQuery) ForShare(opts ...sql.LockOption) *PreimageSharePartnerQuery {
	if pspq.driver.Dialect() == dialect.Postgres {
		pspq.Unique(false)
	}
	pspq.modifiers = append(pspq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return pspq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (pspq *PreimageSharePartnerQuery) Modify(modifiers ...func(s *sql.Selector)) *PreimageSharePartnerSelect {
	pspq.modifiers = append(pspq.modifiers, modifiers...)
	return pspq.Select()
}

// PreimageSharePartnerGroupBy is the group-by builder for PreimageSharePartner entities.
type PreimageSharePartnerGroupBy struct {
	selector
	build *PreimageSharePartnerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pspgb *PreimageSharePartnerGroupBy) Aggregate(fns ...AggregateFunc) *PreimageSharePartnerGroupBy {
	pspgb.fns = append(pspgb.fns, fns...)
	return pspgb
}

// Scan applies the selector query and scans the result into the given value.
func (pspgb *PreimageSharePartnerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pspgb.build.ctx, ent.OpQueryGroupBy)
	if err := pspgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PreimageSharePartnerQuery, *PreimageSharePartnerGroupBy](ctx, pspgb.build, pspgb, pspgb.build.inters, v)
}

func (pspgb *PreimageSharePartnerGroupBy) sqlScan(ctx context.Context, root *PreimageSharePartnerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pspgb.fns))
	for _, fn := range pspgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pspgb.flds)+len(pspgb.fns))
		for _, f := range *pspgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pspgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pspgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PreimageSharePartnerSelect is the builder for selecting fields of PreimageSharePartner entities.
type PreimageSharePartnerSelect struct {
	*PreimageSharePartnerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (psps *PreimageSharePartnerSelect) Aggregate(fns ...AggregateFunc) *PreimageSharePartnerSelect {
	psps.fns = append(psps.fns, fns...)
	return psps
}

// Scan applies the selector query and scans the result into the given value.
func (psps *PreimageSharePartnerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, psps.ctx, ent.OpQuerySelect)
	if err := psps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PreimageSharePartnerQuery, *PreimageSharePartnerSelect](ctx, psps.PreimageSharePartnerQuery, psps, psps.inters, v)
}

func (psps *PreimageSharePartnerSelect) sqlScan(ctx context.Context, root *PreimageSharePartnerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(psps.fns))
	for _, fn := range psps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*psps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := psps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (psps *PreimageSharePartnerSelect) Modify(modifiers ...func(s *sql.Selector)) *PreimageSharePartnerSelect {
	psps.modifiers = append(psps.modifiers, modifiers...)
	return psps
}
