// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/lightsparkdev/spark-go/so/ent/depositaddress"
	"github.com/lightsparkdev/spark-go/so/ent/schema"
	"github.com/lightsparkdev/spark-go/so/ent/signingkeyshare"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	depositaddressMixin := schema.DepositAddress{}.Mixin()
	depositaddressMixinFields0 := depositaddressMixin[0].Fields()
	_ = depositaddressMixinFields0
	depositaddressFields := schema.DepositAddress{}.Fields()
	_ = depositaddressFields
	// depositaddressDescCreateTime is the schema descriptor for create_time field.
	depositaddressDescCreateTime := depositaddressMixinFields0[1].Descriptor()
	// depositaddress.DefaultCreateTime holds the default value on creation for the create_time field.
	depositaddress.DefaultCreateTime = depositaddressDescCreateTime.Default.(func() time.Time)
	// depositaddressDescUpdateTime is the schema descriptor for update_time field.
	depositaddressDescUpdateTime := depositaddressMixinFields0[2].Descriptor()
	// depositaddress.DefaultUpdateTime holds the default value on creation for the update_time field.
	depositaddress.DefaultUpdateTime = depositaddressDescUpdateTime.Default.(func() time.Time)
	// depositaddress.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	depositaddress.UpdateDefaultUpdateTime = depositaddressDescUpdateTime.UpdateDefault.(func() time.Time)
	// depositaddressDescAddress is the schema descriptor for address field.
	depositaddressDescAddress := depositaddressFields[0].Descriptor()
	// depositaddress.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	depositaddress.AddressValidator = depositaddressDescAddress.Validators[0].(func(string) error)
	// depositaddressDescID is the schema descriptor for id field.
	depositaddressDescID := depositaddressMixinFields0[0].Descriptor()
	// depositaddress.DefaultID holds the default value on creation for the id field.
	depositaddress.DefaultID = depositaddressDescID.Default.(func() uuid.UUID)
	signingkeyshareMixin := schema.SigningKeyshare{}.Mixin()
	signingkeyshareMixinFields0 := signingkeyshareMixin[0].Fields()
	_ = signingkeyshareMixinFields0
	signingkeyshareFields := schema.SigningKeyshare{}.Fields()
	_ = signingkeyshareFields
	// signingkeyshareDescCreateTime is the schema descriptor for create_time field.
	signingkeyshareDescCreateTime := signingkeyshareMixinFields0[1].Descriptor()
	// signingkeyshare.DefaultCreateTime holds the default value on creation for the create_time field.
	signingkeyshare.DefaultCreateTime = signingkeyshareDescCreateTime.Default.(func() time.Time)
	// signingkeyshareDescUpdateTime is the schema descriptor for update_time field.
	signingkeyshareDescUpdateTime := signingkeyshareMixinFields0[2].Descriptor()
	// signingkeyshare.DefaultUpdateTime holds the default value on creation for the update_time field.
	signingkeyshare.DefaultUpdateTime = signingkeyshareDescUpdateTime.Default.(func() time.Time)
	// signingkeyshare.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	signingkeyshare.UpdateDefaultUpdateTime = signingkeyshareDescUpdateTime.UpdateDefault.(func() time.Time)
	// signingkeyshareDescID is the schema descriptor for id field.
	signingkeyshareDescID := signingkeyshareMixinFields0[0].Descriptor()
	// signingkeyshare.DefaultID holds the default value on creation for the id field.
	signingkeyshare.DefaultID = signingkeyshareDescID.Default.(func() uuid.UUID)
}
