// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark-go/so/ent/predicate"
	"github.com/lightsparkdev/spark-go/so/ent/tokenissuance"
	"github.com/lightsparkdev/spark-go/so/ent/tokentransactionreceipt"
)

// TokenIssuanceQuery is the builder for querying TokenIssuance entities.
type TokenIssuanceQuery struct {
	config
	ctx                                 *QueryContext
	order                               []tokenissuance.OrderOption
	inters                              []Interceptor
	predicates                          []predicate.TokenIssuance
	withTokenTransactionReceiptIssuance *TokenTransactionReceiptQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TokenIssuanceQuery builder.
func (tiq *TokenIssuanceQuery) Where(ps ...predicate.TokenIssuance) *TokenIssuanceQuery {
	tiq.predicates = append(tiq.predicates, ps...)
	return tiq
}

// Limit the number of records to be returned by this query.
func (tiq *TokenIssuanceQuery) Limit(limit int) *TokenIssuanceQuery {
	tiq.ctx.Limit = &limit
	return tiq
}

// Offset to start from.
func (tiq *TokenIssuanceQuery) Offset(offset int) *TokenIssuanceQuery {
	tiq.ctx.Offset = &offset
	return tiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tiq *TokenIssuanceQuery) Unique(unique bool) *TokenIssuanceQuery {
	tiq.ctx.Unique = &unique
	return tiq
}

// Order specifies how the records should be ordered.
func (tiq *TokenIssuanceQuery) Order(o ...tokenissuance.OrderOption) *TokenIssuanceQuery {
	tiq.order = append(tiq.order, o...)
	return tiq
}

// QueryTokenTransactionReceiptIssuance chains the current query on the "token_transaction_receipt_issuance" edge.
func (tiq *TokenIssuanceQuery) QueryTokenTransactionReceiptIssuance() *TokenTransactionReceiptQuery {
	query := (&TokenTransactionReceiptClient{config: tiq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tiq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tokenissuance.Table, tokenissuance.FieldID, selector),
			sqlgraph.To(tokentransactionreceipt.Table, tokentransactionreceipt.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, tokenissuance.TokenTransactionReceiptIssuanceTable, tokenissuance.TokenTransactionReceiptIssuanceColumn),
		)
		fromU = sqlgraph.SetNeighbors(tiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TokenIssuance entity from the query.
// Returns a *NotFoundError when no TokenIssuance was found.
func (tiq *TokenIssuanceQuery) First(ctx context.Context) (*TokenIssuance, error) {
	nodes, err := tiq.Limit(1).All(setContextOp(ctx, tiq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tokenissuance.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tiq *TokenIssuanceQuery) FirstX(ctx context.Context) *TokenIssuance {
	node, err := tiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TokenIssuance ID from the query.
// Returns a *NotFoundError when no TokenIssuance ID was found.
func (tiq *TokenIssuanceQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tiq.Limit(1).IDs(setContextOp(ctx, tiq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tokenissuance.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tiq *TokenIssuanceQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TokenIssuance entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TokenIssuance entity is found.
// Returns a *NotFoundError when no TokenIssuance entities are found.
func (tiq *TokenIssuanceQuery) Only(ctx context.Context) (*TokenIssuance, error) {
	nodes, err := tiq.Limit(2).All(setContextOp(ctx, tiq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tokenissuance.Label}
	default:
		return nil, &NotSingularError{tokenissuance.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tiq *TokenIssuanceQuery) OnlyX(ctx context.Context) *TokenIssuance {
	node, err := tiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TokenIssuance ID in the query.
// Returns a *NotSingularError when more than one TokenIssuance ID is found.
// Returns a *NotFoundError when no entities are found.
func (tiq *TokenIssuanceQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tiq.Limit(2).IDs(setContextOp(ctx, tiq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tokenissuance.Label}
	default:
		err = &NotSingularError{tokenissuance.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tiq *TokenIssuanceQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TokenIssuances.
func (tiq *TokenIssuanceQuery) All(ctx context.Context) ([]*TokenIssuance, error) {
	ctx = setContextOp(ctx, tiq.ctx, ent.OpQueryAll)
	if err := tiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TokenIssuance, *TokenIssuanceQuery]()
	return withInterceptors[[]*TokenIssuance](ctx, tiq, qr, tiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tiq *TokenIssuanceQuery) AllX(ctx context.Context) []*TokenIssuance {
	nodes, err := tiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TokenIssuance IDs.
func (tiq *TokenIssuanceQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tiq.ctx.Unique == nil && tiq.path != nil {
		tiq.Unique(true)
	}
	ctx = setContextOp(ctx, tiq.ctx, ent.OpQueryIDs)
	if err = tiq.Select(tokenissuance.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tiq *TokenIssuanceQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tiq *TokenIssuanceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tiq.ctx, ent.OpQueryCount)
	if err := tiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tiq, querierCount[*TokenIssuanceQuery](), tiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tiq *TokenIssuanceQuery) CountX(ctx context.Context) int {
	count, err := tiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tiq *TokenIssuanceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tiq.ctx, ent.OpQueryExist)
	switch _, err := tiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tiq *TokenIssuanceQuery) ExistX(ctx context.Context) bool {
	exist, err := tiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TokenIssuanceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tiq *TokenIssuanceQuery) Clone() *TokenIssuanceQuery {
	if tiq == nil {
		return nil
	}
	return &TokenIssuanceQuery{
		config:                              tiq.config,
		ctx:                                 tiq.ctx.Clone(),
		order:                               append([]tokenissuance.OrderOption{}, tiq.order...),
		inters:                              append([]Interceptor{}, tiq.inters...),
		predicates:                          append([]predicate.TokenIssuance{}, tiq.predicates...),
		withTokenTransactionReceiptIssuance: tiq.withTokenTransactionReceiptIssuance.Clone(),
		// clone intermediate query.
		sql:  tiq.sql.Clone(),
		path: tiq.path,
	}
}

// WithTokenTransactionReceiptIssuance tells the query-builder to eager-load the nodes that are connected to
// the "token_transaction_receipt_issuance" edge. The optional arguments are used to configure the query builder of the edge.
func (tiq *TokenIssuanceQuery) WithTokenTransactionReceiptIssuance(opts ...func(*TokenTransactionReceiptQuery)) *TokenIssuanceQuery {
	query := (&TokenTransactionReceiptClient{config: tiq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tiq.withTokenTransactionReceiptIssuance = query
	return tiq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TokenIssuance.Query().
//		GroupBy(tokenissuance.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tiq *TokenIssuanceQuery) GroupBy(field string, fields ...string) *TokenIssuanceGroupBy {
	tiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TokenIssuanceGroupBy{build: tiq}
	grbuild.flds = &tiq.ctx.Fields
	grbuild.label = tokenissuance.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.TokenIssuance.Query().
//		Select(tokenissuance.FieldCreateTime).
//		Scan(ctx, &v)
func (tiq *TokenIssuanceQuery) Select(fields ...string) *TokenIssuanceSelect {
	tiq.ctx.Fields = append(tiq.ctx.Fields, fields...)
	sbuild := &TokenIssuanceSelect{TokenIssuanceQuery: tiq}
	sbuild.label = tokenissuance.Label
	sbuild.flds, sbuild.scan = &tiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TokenIssuanceSelect configured with the given aggregations.
func (tiq *TokenIssuanceQuery) Aggregate(fns ...AggregateFunc) *TokenIssuanceSelect {
	return tiq.Select().Aggregate(fns...)
}

func (tiq *TokenIssuanceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tiq); err != nil {
				return err
			}
		}
	}
	for _, f := range tiq.ctx.Fields {
		if !tokenissuance.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tiq.path != nil {
		prev, err := tiq.path(ctx)
		if err != nil {
			return err
		}
		tiq.sql = prev
	}
	return nil
}

func (tiq *TokenIssuanceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TokenIssuance, error) {
	var (
		nodes       = []*TokenIssuance{}
		_spec       = tiq.querySpec()
		loadedTypes = [1]bool{
			tiq.withTokenTransactionReceiptIssuance != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TokenIssuance).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TokenIssuance{config: tiq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tiq.withTokenTransactionReceiptIssuance; query != nil {
		if err := tiq.loadTokenTransactionReceiptIssuance(ctx, query, nodes, nil,
			func(n *TokenIssuance, e *TokenTransactionReceipt) { n.Edges.TokenTransactionReceiptIssuance = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tiq *TokenIssuanceQuery) loadTokenTransactionReceiptIssuance(ctx context.Context, query *TokenTransactionReceiptQuery, nodes []*TokenIssuance, init func(*TokenIssuance), assign func(*TokenIssuance, *TokenTransactionReceipt)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*TokenIssuance)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.TokenTransactionReceipt(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tokenissuance.TokenTransactionReceiptIssuanceColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.token_issuance_token_transaction_receipt_issuance
		if fk == nil {
			return fmt.Errorf(`foreign-key "token_issuance_token_transaction_receipt_issuance" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "token_issuance_token_transaction_receipt_issuance" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (tiq *TokenIssuanceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tiq.querySpec()
	_spec.Node.Columns = tiq.ctx.Fields
	if len(tiq.ctx.Fields) > 0 {
		_spec.Unique = tiq.ctx.Unique != nil && *tiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tiq.driver, _spec)
}

func (tiq *TokenIssuanceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tokenissuance.Table, tokenissuance.Columns, sqlgraph.NewFieldSpec(tokenissuance.FieldID, field.TypeUUID))
	_spec.From = tiq.sql
	if unique := tiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tiq.path != nil {
		_spec.Unique = true
	}
	if fields := tiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tokenissuance.FieldID)
		for i := range fields {
			if fields[i] != tokenissuance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tiq *TokenIssuanceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tiq.driver.Dialect())
	t1 := builder.Table(tokenissuance.Table)
	columns := tiq.ctx.Fields
	if len(columns) == 0 {
		columns = tokenissuance.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tiq.sql != nil {
		selector = tiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tiq.ctx.Unique != nil && *tiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tiq.predicates {
		p(selector)
	}
	for _, p := range tiq.order {
		p(selector)
	}
	if offset := tiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TokenIssuanceGroupBy is the group-by builder for TokenIssuance entities.
type TokenIssuanceGroupBy struct {
	selector
	build *TokenIssuanceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tigb *TokenIssuanceGroupBy) Aggregate(fns ...AggregateFunc) *TokenIssuanceGroupBy {
	tigb.fns = append(tigb.fns, fns...)
	return tigb
}

// Scan applies the selector query and scans the result into the given value.
func (tigb *TokenIssuanceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tigb.build.ctx, ent.OpQueryGroupBy)
	if err := tigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TokenIssuanceQuery, *TokenIssuanceGroupBy](ctx, tigb.build, tigb, tigb.build.inters, v)
}

func (tigb *TokenIssuanceGroupBy) sqlScan(ctx context.Context, root *TokenIssuanceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tigb.fns))
	for _, fn := range tigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tigb.flds)+len(tigb.fns))
		for _, f := range *tigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TokenIssuanceSelect is the builder for selecting fields of TokenIssuance entities.
type TokenIssuanceSelect struct {
	*TokenIssuanceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tis *TokenIssuanceSelect) Aggregate(fns ...AggregateFunc) *TokenIssuanceSelect {
	tis.fns = append(tis.fns, fns...)
	return tis
}

// Scan applies the selector query and scans the result into the given value.
func (tis *TokenIssuanceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tis.ctx, ent.OpQuerySelect)
	if err := tis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TokenIssuanceQuery, *TokenIssuanceSelect](ctx, tis.TokenIssuanceQuery, tis, tis.inters, v)
}

func (tis *TokenIssuanceSelect) sqlScan(ctx context.Context, root *TokenIssuanceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tis.fns))
	for _, fn := range tis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
