// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/tokenallowance"
)

// TokenAllowanceDelete is the builder for deleting a TokenAllowance entity.
type TokenAllowanceDelete struct {
	config
	hooks    []Hook
	mutation *TokenAllowanceMutation
}

// Where appends a list predicates to the TokenAllowanceDelete builder.
func (tad *TokenAllowanceDelete) Where(ps ...predicate.TokenAllowance) *TokenAllowanceDelete {
	tad.mutation.Where(ps...)
	return tad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tad *TokenAllowanceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tad.sqlExec, tad.mutation, tad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tad *TokenAllowanceDelete) ExecX(ctx context.Context) int {
	n, err := tad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tad *TokenAllowanceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tokenallowance.Table, sqlgraph.NewFieldSpec(tokenallowance.FieldID, field.TypeUUID))
	if ps := tad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tad.mutation.done = true
	return affected, err
}

// TokenAllowanceDeleteOne is the builder for deleting a single TokenAllowance entity.
type TokenAllowanceDeleteOne struct {
	tad *TokenAllowanceDelete
}

// Where appends a list predicates to the TokenAllowanceDelete builder.
func (tado *TokenAllowanceDeleteOne) Where(ps ...predicate.TokenAllowance) *TokenAllowanceDeleteOne {
	tado.tad.mutation.Where(ps...)
	return tado
}

// Exec executes the deletion query.
func (tado *TokenAllowanceDeleteOne) Exec(ctx context.Context) error {
	n, err := tado.tad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tokenallowance.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tado *TokenAllowanceDeleteOne) ExecX(ctx context.Context) {
	if err := tado.Exec(ctx); err != nil {
		panic(err)
	}
}
