// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/tokenallowance"
	"github.com/lightsparkdev/spark/so/ent/tokencreate"
)

// TokenAllowanceQuery is the builder for querying TokenAllowance entities.
type TokenAllowanceQuery struct {
	config
	ctx             *QueryContext
	order           []tokenallowance.OrderOption
	inters          []Interceptor
	predicates      []predicate.TokenAllowance
	withTokenCreate *TokenCreateQuery
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TokenAllowanceQuery builder.
func (taq *TokenAllowanceQuery) Where(ps ...predicate.TokenAllowance) *TokenAllowanceQuery {
	taq.predicates = append(taq.predicates, ps...)
	return taq
}

// Limit the number of records to be returned by this query.
func (taq *TokenAllowanceQuery) Limit(limit int) *TokenAllowanceQuery {
	taq.ctx.Limit = &limit
	return taq
}

// Offset to start from.
func (taq *TokenAllowanceQuery) Offset(offset int) *TokenAllowanceQuery {
	taq.ctx.Offset = &offset
	return taq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (taq *TokenAllowanceQuery) Unique(unique bool) *TokenAllowanceQuery {
	taq.ctx.Unique = &unique
	return taq
}

// Order specifies how the records should be ordered.
func (taq *TokenAllowanceQuery) Order(o ...tokenallowance.OrderOption) *TokenAllowanceQuery {
	taq.order = append(taq.order, o...)
	return taq
}

// QueryTokenCreate chains the current query on the "token_create" edge.
func (taq *TokenAllowanceQuery) QueryTokenCreate() *TokenCreateQuery {
	query := (&TokenCreateClient{config: taq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := taq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := taq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tokenallowance.Table, tokenallowance.FieldID, selector),
			sqlgraph.To(tokencreate.Table, tokencreate.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tokenallowance.TokenCreateTable, tokenallowance.TokenCreateColumn),
		)
		fromU = sqlgraph.SetNeighbors(taq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TokenAllowance entity from the query.
// Returns a *NotFoundError when no TokenAllowance was found.
func (taq *TokenAllowanceQuery) First(ctx context.Context) (*TokenAllowance, error) {
	nodes, err := taq.Limit(1).All(setContextOp(ctx, taq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tokenallowance.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (taq *TokenAllowanceQuery) FirstX(ctx context.Context) *TokenAllowance {
	node, err := taq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TokenAllowance ID from the query.
// Returns a *NotFoundError when no TokenAllowance ID was found.
func (taq *TokenAllowanceQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = taq.Limit(1).IDs(setContextOp(ctx, taq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tokenallowance.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (taq *TokenAllowanceQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := taq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TokenAllowance entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TokenAllowance entity is found.
// Returns a *NotFoundError when no TokenAllowance entities are found.
func (taq *TokenAllowanceQuery) Only(ctx context.Context) (*TokenAllowance, error) {
	nodes, err := taq.Limit(2).All(setContextOp(ctx, taq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tokenallowance.Label}
	default:
		return nil, &NotSingularError{tokenallowance.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (taq *TokenAllowanceQuery) OnlyX(ctx context.Context) *TokenAllowance {
	node, err := taq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TokenAllowance ID in the query.
// Returns a *NotSingularError when more than one TokenAllowance ID is found.
// Returns a *NotFoundError when no entities are found.
func (taq *TokenAllowanceQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = taq.Limit(2).IDs(setContextOp(ctx, taq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tokenallowance.Label}
	default:
		err = &NotSingularError{tokenallowance.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (taq *TokenAllowanceQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := taq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TokenAllowances.
func (taq *TokenAllowanceQuery) All(ctx context.Context) ([]*TokenAllowance, error) {
	ctx = setContextOp(ctx, taq.ctx, ent.OpQueryAll)
	if err := taq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TokenAllowance, *TokenAllowanceQuery]()
	return withInterceptors[[]*TokenAllowance](ctx, taq, qr, taq.inters)
}

// AllX is like All, but panics if an error occurs.
func (taq *TokenAllowanceQuery) AllX(ctx context.Context) []*TokenAllowance {
	nodes, err := taq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TokenAllowance IDs.
func (taq *TokenAllowanceQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if taq.ctx.Unique == nil && taq.path != nil {
		taq.Unique(true)
	}
	ctx = setContextOp(ctx, taq.ctx, ent.OpQueryIDs)
	if err = taq.Select(tokenallowance.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (taq *TokenAllowanceQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := taq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (taq *TokenAllowanceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, taq.ctx, ent.OpQueryCount)
	if err := taq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, taq, querierCount[*TokenAllowanceQuery](), taq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (taq *TokenAllowanceQuery) CountX(ctx context.Context) int {
	count, err := taq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (taq *TokenAllowanceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, taq.ctx, ent.OpQueryExist)
	switch _, err := taq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (taq *TokenAllowanceQuery) ExistX(ctx context.Context) bool {
	exist, err := taq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TokenAllowanceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (taq *TokenAllowanceQuery) Clone() *TokenAllowanceQuery {
	if taq == nil {
		return nil
	}
	return &TokenAllowanceQuery{
		config:          taq.config,
		ctx:             taq.ctx.Clone(),
		order:           append([]tokenallowance.OrderOption{}, taq.order...),
		inters:          append([]Interceptor{}, taq.inters...),
		predicates:      append([]predicate.TokenAllowance{}, taq.predicates...),
		withTokenCreate: taq.withTokenCreate.Clone(),
		// clone intermediate query.
		sql:       taq.sql.Clone(),
		path:      taq.path,
		modifiers: append([]func(*sql.Selector){}, taq.modifiers...),
	}
}

// WithTokenCreate tells the query-builder to eager-load the nodes that are connected to
// the "token_create" edge. The optional arguments are used to configure the query builder of the edge.
func (taq *TokenAllowanceQuery) WithTokenCreate(opts ...func(*TokenCreateQuery)) *TokenAllowanceQuery {
	query := (&TokenCreateClient{config: taq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	taq.withTokenCreate = query
	return taq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TokenAllowance.Query().
//		GroupBy(tokenallowance.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (taq *TokenAllowanceQuery) GroupBy(field string, fields ...string) *TokenAllowanceGroupBy {
	taq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TokenAllowanceGroupBy{build: taq}
	grbuild.flds = &taq.ctx.Fields
	grbuild.label = tokenallowance.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.TokenAllowance.Query().
//		Select(tokenallowance.FieldCreateTime).
//		Scan(ctx, &v)
func (taq *TokenAllowanceQuery) Select(fields ...string) *TokenAllowanceSelect {
	taq.ctx.Fields = append(taq.ctx.Fields, fields...)
	sbuild := &TokenAllowanceSelect{TokenAllowanceQuery: taq}
	sbuild.label = tokenallowance.Label
	sbuild.flds, sbuild.scan = &taq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TokenAllowanceSelect configured with the given aggregations.
func (taq *TokenAllowanceQuery) Aggregate(fns ...AggregateFunc) *TokenAllowanceSelect {
	return taq.Select().Aggregate(fns...)
}

func (taq *TokenAllowanceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range taq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, taq); err != nil {
				return err
			}
		}
	}
	for _, f := range taq.ctx.Fields {
		if !tokenallowance.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if taq.path != nil {
		prev, err := taq.path(ctx)
		if err != nil {
			return err
		}
		taq.sql = prev
	}
	return nil
}

func (taq *TokenAllowanceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TokenAllowance, error) {
	var (
		nodes       = []*TokenAllowance{}
		_spec       = taq.querySpec()
		loadedTypes = [1]bool{
			taq.withTokenCreate != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TokenAllowance).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TokenAllowance{config: taq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(taq.modifiers) > 0 {
		_spec.Modifiers = taq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, taq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := taq.withTokenCreate; query != nil {
		if err := taq.loadTokenCreate(ctx, query, nodes, nil,
			func(n *TokenAllowance, e *TokenCreate) { n.Edges.TokenCreate = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (taq *TokenAllowanceQuery) loadTokenCreate(ctx context.Context, query *TokenCreateQuery, nodes []*TokenAllowance, init func(*TokenAllowance), assign func(*TokenAllowance, *TokenCreate)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TokenAllowance)
	for i := range nodes {
		fk := nodes[i].TokenCreateID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tokencreate.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "token_create_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (taq *TokenAllowanceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := taq.querySpec()
	if len(taq.modifiers) > 0 {
		_spec.Modifiers = taq.modifiers
	}
	_spec.Node.Columns = taq.ctx.Fields
	if len(taq.ctx.Fields) > 0 {
		_spec.Unique = taq.ctx.Unique != nil && *taq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, taq.driver, _spec)
}

func (taq *TokenAllowanceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tokenallowance.Table, tokenallowance.Columns, sqlgraph.NewFieldSpec(tokenallowance.FieldID, field.TypeUUID))
	_spec.From = taq.sql
	if unique := taq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if taq.path != nil {
		_spec.Unique = true
	}
	if fields := taq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tokenallowance.FieldID)
		for i := range fields {
			if fields[i] != tokenallowance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if taq.withTokenCreate != nil {
			_spec.Node.AddColumnOnce(tokenallowance.FieldTokenCreateID)
		}
	}
	if ps := taq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := taq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := taq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := taq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (taq *TokenAllowanceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(taq.driver.Dialect())
	t1 := builder.Table(tokenallowance.Table)
	columns := taq.ctx.Fields
	if len(columns) == 0 {
		columns = tokenallowance.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if taq.sql != nil {
		selector = taq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if taq.ctx.Unique != nil && *taq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range taq.modifiers {
		m(selector)
	}
	for _, p := range taq.predicates {
		p(selector)
	}
	for _, p := range taq.order {
		p(selector)
	}
	if offset := taq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := taq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (taq *TokenAllowanceQuery) ForUpdate(opts ...sql.LockOption) *TokenAllowanceQuery {
	if taq.driver.Dialect() == dialect.Postgres {
		taq.Unique(false)
	}
	taq.modifiers = append(taq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return taq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (taq *TokenAllowanceQuery) ForShare(opts ...sql.LockOption) *TokenAllowanceQuery {
	if taq.driver.Dialect() == dialect.Postgres {
		taq.Unique(false)
	}
	taq.modifiers = append(taq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return taq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (taq *TokenAllowanceQuery) Modify(modifiers ...func(s *sql.Selector)) *TokenAllowanceSelect {
	taq.modifiers = append(taq.modifiers, modifiers...)
	return taq.Select()
}

// TokenAllowanceGroupBy is the group-by builder for TokenAllowance entities.
type TokenAllowanceGroupBy struct {
	selector
	build *TokenAllowanceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tagb *TokenAllowanceGroupBy) Aggregate(fns ...AggregateFunc) *TokenAllowanceGroupBy {
	tagb.fns = append(tagb.fns, fns...)
	return tagb
}

// Scan applies the selector query and scans the result into the given value.
func (tagb *TokenAllowanceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tagb.build.ctx, ent.OpQueryGroupBy)
	if err := tagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TokenAllowanceQuery, *TokenAllowanceGroupBy](ctx, tagb.build, tagb, tagb.build.inters, v)
}

func (tagb *TokenAllowanceGroupBy) sqlScan(ctx context.Context, root *TokenAllowanceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tagb.fns))
	for _, fn := range tagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tagb.flds)+len(tagb.fns))
		for _, f := range *tagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TokenAllowanceSelect is the builder for selecting fields of TokenAllowance entities.
type TokenAllowanceSelect struct {
	*TokenAllowanceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tas *TokenAllowanceSelect) Aggregate(fns ...AggregateFunc) *TokenAllowanceSelect {
	tas.fns = append(tas.fns, fns...)
	return tas
}

// Scan applies the selector query and scans the result into the given value.
func (tas *TokenAllowanceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tas.ctx, ent.OpQuerySelect)
	if err := tas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TokenAllowanceQuery, *TokenAllowanceSelect](ctx, tas.TokenAllowanceQuery, tas, tas.inters, v)
}

func (tas *TokenAllowanceSelect) sqlScan(ctx context.Context, root *TokenAllowanceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tas.fns))
	for _, fn := range tas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tas *TokenAllowanceSelect) Modify(modifiers ...func(s *sql.Selector)) *TokenAllowanceSelect {
	tas.modifiers = append(tas.modifiers, modifiers...)
	return tas
}
