// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/common/btcnetwork"
	"github.com/lightsparkdev/spark/common/keys"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
	"github.com/lightsparkdev/spark/so/ent/tokenallowance"
	"github.com/lightsparkdev/spark/so/ent/tokencreate"
)

// TokenAllowanceCreate is the builder for creating a TokenAllowance entity.
type TokenAllowanceCreate struct {
	config
	mutation *TokenAllowanceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "create_time" field.
func (tac *TokenAllowanceCreate) SetCreateTime(t time.Time) *TokenAllowanceCreate {
	tac.mutation.SetCreateTime(t)
	return tac
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (tac *TokenAllowanceCreate) SetNillableCreateTime(t *time.Time) *TokenAllowanceCreate {
	if t != nil {
		tac.SetCreateTime(*t)
	}
	return tac
}

// SetUpdateTime sets the "update_time" field.
func (tac *TokenAllowanceCreate) SetUpdateTime(t time.Time) *TokenAllowanceCreate {
	tac.mutation.SetUpdateTime(t)
	return tac
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (tac *TokenAllowanceCreate) SetNillableUpdateTime(t *time.Time) *TokenAllowanceCreate {
	if t != nil {
		tac.SetUpdateTime(*t)
	}
	return tac
}

// SetAllowanceID sets the "allowance_id" field.
func (tac *TokenAllowanceCreate) SetAllowanceID(u uuid.UUID) *TokenAllowanceCreate {
	tac.mutation.SetAllowanceID(u)
	return tac
}

// SetStatus sets the "status" field.
func (tac *TokenAllowanceCreate) SetStatus(sas schematype.TokenAllowanceStatus) *TokenAllowanceCreate {
	tac.mutation.SetStatus(sas)
	return tac
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tac *TokenAllowanceCreate) SetNillableStatus(sas *schematype.TokenAllowanceStatus) *TokenAllowanceCreate {
	if sas != nil {
		tac.SetStatus(*sas)
	}
	return tac
}

// SetOwnerPublicKey sets the "owner_public_key" field.
func (tac *TokenAllowanceCreate) SetOwnerPublicKey(k keys.Public) *TokenAllowanceCreate {
	tac.mutation.SetOwnerPublicKey(k)
	return tac
}

// SetSpenderPublicKey sets the "spender_public_key" field.
func (tac *TokenAllowanceCreate) SetSpenderPublicKey(k keys.Public) *TokenAllowanceCreate {
	tac.mutation.SetSpenderPublicKey(k)
	return tac
}

// SetTokenIdentifier sets the "token_identifier" field.
func (tac *TokenAllowanceCreate) SetTokenIdentifier(b []byte) *TokenAllowanceCreate {
	tac.mutation.SetTokenIdentifier(b)
	return tac
}

// SetTokenCreateID sets the "token_create_id" field.
func (tac *TokenAllowanceCreate) SetTokenCreateID(u uuid.UUID) *TokenAllowanceCreate {
	tac.mutation.SetTokenCreateID(u)
	return tac
}

// SetPerTransactionCap sets the "per_transaction_cap" field.
func (tac *TokenAllowanceCreate) SetPerTransactionCap(b []byte) *TokenAllowanceCreate {
	tac.mutation.SetPerTransactionCap(b)
	return tac
}

// SetTotalLimit sets the "total_limit" field.
func (tac *TokenAllowanceCreate) SetTotalLimit(b []byte) *TokenAllowanceCreate {
	tac.mutation.SetTotalLimit(b)
	return tac
}

// SetSpentAmount sets the "spent_amount" field.
func (tac *TokenAllowanceCreate) SetSpentAmount(b []byte) *TokenAllowanceCreate {
	tac.mutation.SetSpentAmount(b)
	return tac
}

// SetRecipientAllowlist sets the "recipient_allowlist" field.
func (tac *TokenAllowanceCreate) SetRecipientAllowlist(u [][]uint8) *TokenAllowanceCreate {
	tac.mutation.SetRecipientAllowlist(u)
	return tac
}

// SetExpiryTime sets the "expiry_time" field.
func (tac *TokenAllowanceCreate) SetExpiryTime(t time.Time) *TokenAllowanceCreate {
	tac.mutation.SetExpiryTime(t)
	return tac
}

// SetNetwork sets the "network" field.
func (tac *TokenAllowanceCreate) SetNetwork(b btcnetwork.Network) *TokenAllowanceCreate {
	tac.mutation.SetNetwork(b)
	return tac
}

// SetOwnerSignature sets the "owner_signature" field.
func (tac *TokenAllowanceCreate) SetOwnerSignature(b []byte) *TokenAllowanceCreate {
	tac.mutation.SetOwnerSignature(b)
	return tac
}

// SetStatementHash sets the "statement_hash" field.
func (tac *TokenAllowanceCreate) SetStatementHash(b []byte) *TokenAllowanceCreate {
	tac.mutation.SetStatementHash(b)
	return tac
}

// SetVersion sets the "version" field.
func (tac *TokenAllowanceCreate) SetVersion(u uint64) *TokenAllowanceCreate {
	tac.mutation.SetVersion(u)
	return tac
}

// SetOwnerProvidedTimestamp sets the "owner_provided_timestamp" field.
func (tac *TokenAllowanceCreate) SetOwnerProvidedTimestamp(u uint64) *TokenAllowanceCreate {
	tac.mutation.SetOwnerProvidedTimestamp(u)
	return tac
}

// SetOwnerProvidedRevokeTimestamp sets the "owner_provided_revoke_timestamp" field.
func (tac *TokenAllowanceCreate) SetOwnerProvidedRevokeTimestamp(u uint64) *TokenAllowanceCreate {
	tac.mutation.SetOwnerProvidedRevokeTimestamp(u)
	return tac
}

// SetNillableOwnerProvidedRevokeTimestamp sets the "owner_provided_revoke_timestamp" field if the given value is not nil.
func (tac *TokenAllowanceCreate) SetNillableOwnerProvidedRevokeTimestamp(u *uint64) *TokenAllowanceCreate {
	if u != nil {
		tac.SetOwnerProvidedRevokeTimestamp(*u)
	}
	return tac
}

// SetRevokeSignature sets the "revoke_signature" field.
func (tac *TokenAllowanceCreate) SetRevokeSignature(b []byte) *TokenAllowanceCreate {
	tac.mutation.SetRevokeSignature(b)
	return tac
}

// SetID sets the "id" field.
func (tac *TokenAllowanceCreate) SetID(u uuid.UUID) *TokenAllowanceCreate {
	tac.mutation.SetID(u)
	return tac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tac *TokenAllowanceCreate) SetNillableID(u *uuid.UUID) *TokenAllowanceCreate {
	if u != nil {
		tac.SetID(*u)
	}
	return tac
}

// SetTokenCreate sets the "token_create" edge to the TokenCreate entity.
func (tac *TokenAllowanceCreate) SetTokenCreate(t *TokenCreate) *TokenAllowanceCreate {
	return tac.SetTokenCreateID(t.ID)
}

// Mutation returns the TokenAllowanceMutation object of the builder.
func (tac *TokenAllowanceCreate) Mutation() *TokenAllowanceMutation {
	return tac.mutation
}

// Save creates the TokenAllowance in the database.
func (tac *TokenAllowanceCreate) Save(ctx context.Context) (*TokenAllowance, error) {
	tac.defaults()
	return withHooks(ctx, tac.sqlSave, tac.mutation, tac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tac *TokenAllowanceCreate) SaveX(ctx context.Context) *TokenAllowance {
	v, err := tac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tac *TokenAllowanceCreate) Exec(ctx context.Context) error {
	_, err := tac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tac *TokenAllowanceCreate) ExecX(ctx context.Context) {
	if err := tac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tac *TokenAllowanceCreate) defaults() {
	if _, ok := tac.mutation.CreateTime(); !ok {
		v := tokenallowance.DefaultCreateTime()
		tac.mutation.SetCreateTime(v)
	}
	if _, ok := tac.mutation.UpdateTime(); !ok {
		v := tokenallowance.DefaultUpdateTime()
		tac.mutation.SetUpdateTime(v)
	}
	if _, ok := tac.mutation.Status(); !ok {
		v := tokenallowance.DefaultStatus
		tac.mutation.SetStatus(v)
	}
	if _, ok := tac.mutation.SpentAmount(); !ok {
		v := tokenallowance.DefaultSpentAmount
		tac.mutation.SetSpentAmount(v)
	}
	if _, ok := tac.mutation.ID(); !ok {
		v := tokenallowance.DefaultID()
		tac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tac *TokenAllowanceCreate) check() error {
	if _, ok := tac.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "TokenAllowance.create_time"`)}
	}
	if _, ok := tac.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "TokenAllowance.update_time"`)}
	}
	if _, ok := tac.mutation.AllowanceID(); !ok {
		return &ValidationError{Name: "allowance_id", err: errors.New(`ent: missing required field "TokenAllowance.allowance_id"`)}
	}
	if _, ok := tac.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TokenAllowance.status"`)}
	}
	if v, ok := tac.mutation.Status(); ok {
		if err := tokenallowance.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TokenAllowance.status": %w`, err)}
		}
	}
	if _, ok := tac.mutation.OwnerPublicKey(); !ok {
		return &ValidationError{Name: "owner_public_key", err: errors.New(`ent: missing required field "TokenAllowance.owner_public_key"`)}
	}
	if _, ok := tac.mutation.SpenderPublicKey(); !ok {
		return &ValidationError{Name: "spender_public_key", err: errors.New(`ent: missing required field "TokenAllowance.spender_public_key"`)}
	}
	if _, ok := tac.mutation.TokenIdentifier(); !ok {
		return &ValidationError{Name: "token_identifier", err: errors.New(`ent: missing required field "TokenAllowance.token_identifier"`)}
	}
	if _, ok := tac.mutation.TokenCreateID(); !ok {
		return &ValidationError{Name: "token_create_id", err: errors.New(`ent: missing required field "TokenAllowance.token_create_id"`)}
	}
	if _, ok := tac.mutation.PerTransactionCap(); !ok {
		return &ValidationError{Name: "per_transaction_cap", err: errors.New(`ent: missing required field "TokenAllowance.per_transaction_cap"`)}
	}
	if _, ok := tac.mutation.TotalLimit(); !ok {
		return &ValidationError{Name: "total_limit", err: errors.New(`ent: missing required field "TokenAllowance.total_limit"`)}
	}
	if _, ok := tac.mutation.SpentAmount(); !ok {
		return &ValidationError{Name: "spent_amount", err: errors.New(`ent: missing required field "TokenAllowance.spent_amount"`)}
	}
	if _, ok := tac.mutation.ExpiryTime(); !ok {
		return &ValidationError{Name: "expiry_time", err: errors.New(`ent: missing required field "TokenAllowance.expiry_time"`)}
	}
	if _, ok := tac.mutation.Network(); !ok {
		return &ValidationError{Name: "network", err: errors.New(`ent: missing required field "TokenAllowance.network"`)}
	}
	if v, ok := tac.mutation.Network(); ok {
		if err := tokenallowance.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "TokenAllowance.network": %w`, err)}
		}
	}
	if _, ok := tac.mutation.OwnerSignature(); !ok {
		return &ValidationError{Name: "owner_signature", err: errors.New(`ent: missing required field "TokenAllowance.owner_signature"`)}
	}
	if v, ok := tac.mutation.OwnerSignature(); ok {
		if err := tokenallowance.OwnerSignatureValidator(v); err != nil {
			return &ValidationError{Name: "owner_signature", err: fmt.Errorf(`ent: validator failed for field "TokenAllowance.owner_signature": %w`, err)}
		}
	}
	if _, ok := tac.mutation.StatementHash(); !ok {
		return &ValidationError{Name: "statement_hash", err: errors.New(`ent: missing required field "TokenAllowance.statement_hash"`)}
	}
	if _, ok := tac.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "TokenAllowance.version"`)}
	}
	if _, ok := tac.mutation.OwnerProvidedTimestamp(); !ok {
		return &ValidationError{Name: "owner_provided_timestamp", err: errors.New(`ent: missing required field "TokenAllowance.owner_provided_timestamp"`)}
	}
	if len(tac.mutation.TokenCreateIDs()) == 0 {
		return &ValidationError{Name: "token_create", err: errors.New(`ent: missing required edge "TokenAllowance.token_create"`)}
	}
	return nil
}

func (tac *TokenAllowanceCreate) sqlSave(ctx context.Context) (*TokenAllowance, error) {
	if err := tac.check(); err != nil {
		return nil, err
	}
	_node, _spec := tac.createSpec()
	if err := sqlgraph.CreateNode(ctx, tac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tac.mutation.id = &_node.ID
	tac.mutation.done = true
	return _node, nil
}

func (tac *TokenAllowanceCreate) createSpec() (*TokenAllowance, *sqlgraph.CreateSpec) {
	var (
		_node = &TokenAllowance{config: tac.config}
		_spec = sqlgraph.NewCreateSpec(tokenallowance.Table, sqlgraph.NewFieldSpec(tokenallowance.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = tac.conflict
	if id, ok := tac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tac.mutation.CreateTime(); ok {
		_spec.SetField(tokenallowance.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := tac.mutation.UpdateTime(); ok {
		_spec.SetField(tokenallowance.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := tac.mutation.AllowanceID(); ok {
		_spec.SetField(tokenallowance.FieldAllowanceID, field.TypeUUID, value)
		_node.AllowanceID = value
	}
	if value, ok := tac.mutation.Status(); ok {
		_spec.SetField(tokenallowance.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := tac.mutation.OwnerPublicKey(); ok {
		_spec.SetField(tokenallowance.FieldOwnerPublicKey, field.TypeBytes, value)
		_node.OwnerPublicKey = value
	}
	if value, ok := tac.mutation.SpenderPublicKey(); ok {
		_spec.SetField(tokenallowance.FieldSpenderPublicKey, field.TypeBytes, value)
		_node.SpenderPublicKey = value
	}
	if value, ok := tac.mutation.TokenIdentifier(); ok {
		_spec.SetField(tokenallowance.FieldTokenIdentifier, field.TypeBytes, value)
		_node.TokenIdentifier = value
	}
	if value, ok := tac.mutation.PerTransactionCap(); ok {
		_spec.SetField(tokenallowance.FieldPerTransactionCap, field.TypeBytes, value)
		_node.PerTransactionCap = value
	}
	if value, ok := tac.mutation.TotalLimit(); ok {
		_spec.SetField(tokenallowance.FieldTotalLimit, field.TypeBytes, value)
		_node.TotalLimit = value
	}
	if value, ok := tac.mutation.SpentAmount(); ok {
		_spec.SetField(tokenallowance.FieldSpentAmount, field.TypeBytes, value)
		_node.SpentAmount = value
	}
	if value, ok := tac.mutation.RecipientAllowlist(); ok {
		_spec.SetField(tokenallowance.FieldRecipientAllowlist, field.TypeJSON, value)
		_node.RecipientAllowlist = value
	}
	if value, ok := tac.mutation.ExpiryTime(); ok {
		_spec.SetField(tokenallowance.FieldExpiryTime, field.TypeTime, value)
		_node.ExpiryTime = value
	}
	if value, ok := tac.mutation.Network(); ok {
		_spec.SetField(tokenallowance.FieldNetwork, field.TypeEnum, value)
		_node.Network = value
	}
	if value, ok := tac.mutation.OwnerSignature(); ok {
		_spec.SetField(tokenallowance.FieldOwnerSignature, field.TypeBytes, value)
		_node.OwnerSignature = value
	}
	if value, ok := tac.mutation.StatementHash(); ok {
		_spec.SetField(tokenallowance.FieldStatementHash, field.TypeBytes, value)
		_node.StatementHash = value
	}
	if value, ok := tac.mutation.Version(); ok {
		_spec.SetField(tokenallowance.FieldVersion, field.TypeUint64, value)
		_node.Version = value
	}
	if value, ok := tac.mutation.OwnerProvidedTimestamp(); ok {
		_spec.SetField(tokenallowance.FieldOwnerProvidedTimestamp, field.TypeUint64, value)
		_node.OwnerProvidedTimestamp = value
	}
	if value, ok := tac.mutation.OwnerProvidedRevokeTimestamp(); ok {
		_spec.SetField(tokenallowance.FieldOwnerProvidedRevokeTimestamp, field.TypeUint64, value)
		_node.OwnerProvidedRevokeTimestamp = value
	}
	if value, ok := tac.mutation.RevokeSignature(); ok {
		_spec.SetField(tokenallowance.FieldRevokeSignature, field.TypeBytes, value)
		_node.RevokeSignature = value
	}
	if nodes := tac.mutation.TokenCreateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tokenallowance.TokenCreateTable,
			Columns: []string{tokenallowance.TokenCreateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tokencreate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TokenCreateID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TokenAllowance.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TokenAllowanceUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (tac *TokenAllowanceCreate) OnConflict(opts ...sql.ConflictOption) *TokenAllowanceUpsertOne {
	tac.conflict = opts
	return &TokenAllowanceUpsertOne{
		create: tac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TokenAllowance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tac *TokenAllowanceCreate) OnConflictColumns(columns ...string) *TokenAllowanceUpsertOne {
	tac.conflict = append(tac.conflict, sql.ConflictColumns(columns...))
	return &TokenAllowanceUpsertOne{
		create: tac,
	}
}

type (
	// TokenAllowanceUpsertOne is the builder for "upsert"-ing
	//  one TokenAllowance node.
	TokenAllowanceUpsertOne struct {
		create *TokenAllowanceCreate
	}

	// TokenAllowanceUpsert is the "OnConflict" setter.
	TokenAllowanceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "update_time" field.
func (u *TokenAllowanceUpsert) SetUpdateTime(v time.Time) *TokenAllowanceUpsert {
	u.Set(tokenallowance.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TokenAllowanceUpsert) UpdateUpdateTime() *TokenAllowanceUpsert {
	u.SetExcluded(tokenallowance.FieldUpdateTime)
	return u
}

// SetStatus sets the "status" field.
func (u *TokenAllowanceUpsert) SetStatus(v schematype.TokenAllowanceStatus) *TokenAllowanceUpsert {
	u.Set(tokenallowance.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TokenAllowanceUpsert) UpdateStatus() *TokenAllowanceUpsert {
	u.SetExcluded(tokenallowance.FieldStatus)
	return u
}

// SetSpentAmount sets the "spent_amount" field.
func (u *TokenAllowanceUpsert) SetSpentAmount(v []byte) *TokenAllowanceUpsert {
	u.Set(tokenallowance.FieldSpentAmount, v)
	return u
}

// UpdateSpentAmount sets the "spent_amount" field to the value that was provided on create.
func (u *TokenAllowanceUpsert) UpdateSpentAmount() *TokenAllowanceUpsert {
	u.SetExcluded(tokenallowance.FieldSpentAmount)
	return u
}

// SetOwnerProvidedRevokeTimestamp sets the "owner_provided_revoke_timestamp" field.
func (u *TokenAllowanceUpsert) SetOwnerProvidedRevokeTimestamp(v uint64) *TokenAllowanceUpsert {
	u.Set(tokenallowance.FieldOwnerProvidedRevokeTimestamp, v)
	return u
}

// UpdateOwnerProvidedRevokeTimestamp sets the "owner_provided_revoke_timestamp" field to the value that was provided on create.
func (u *TokenAllowanceUpsert) UpdateOwnerProvidedRevokeTimestamp() *TokenAllowanceUpsert {
	u.SetExcluded(tokenallowance.FieldOwnerProvidedRevokeTimestamp)
	return u
}

// AddOwnerProvidedRevokeTimestamp adds v to the "owner_provided_revoke_timestamp" field.
func (u *TokenAllowanceUpsert) AddOwnerProvidedRevokeTimestamp(v uint64) *TokenAllowanceUpsert {
	u.Add(tokenallowance.FieldOwnerProvidedRevokeTimestamp, v)
	return u
}

// ClearOwnerProvidedRevokeTimestamp clears the value of the "owner_provided_revoke_timestamp" field.
func (u *TokenAllowanceUpsert) ClearOwnerProvidedRevokeTimestamp() *TokenAllowanceUpsert {
	u.SetNull(tokenallowance.FieldOwnerProvidedRevokeTimestamp)
	return u
}

// SetRevokeSignature sets the "revoke_signature" field.
func (u *TokenAllowanceUpsert) SetRevokeSignature(v []byte) *TokenAllowanceUpsert {
	u.Set(tokenallowance.FieldRevokeSignature, v)
	return u
}

// UpdateRevokeSignature sets the "revoke_signature" field to the value that was provided on create.
func (u *TokenAllowanceUpsert) UpdateRevokeSignature() *TokenAllowanceUpsert {
	u.SetExcluded(tokenallowance.FieldRevokeSignature)
	return u
}

// ClearRevokeSignature clears the value of the "revoke_signature" field.
func (u *TokenAllowanceUpsert) ClearRevokeSignature() *TokenAllowanceUpsert {
	u.SetNull(tokenallowance.FieldRevokeSignature)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TokenAllowance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tokenallowance.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TokenAllowanceUpsertOne) UpdateNewValues() *TokenAllowanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(tokenallowance.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(tokenallowance.FieldCreateTime)
		}
		if _, exists := u.create.mutation.AllowanceID(); exists {
			s.SetIgnore(tokenallowance.FieldAllowanceID)
		}
		if _, exists := u.create.mutation.OwnerPublicKey(); exists {
			s.SetIgnore(tokenallowance.FieldOwnerPublicKey)
		}
		if _, exists := u.create.mutation.SpenderPublicKey(); exists {
			s.SetIgnore(tokenallowance.FieldSpenderPublicKey)
		}
		if _, exists := u.create.mutation.TokenIdentifier(); exists {
			s.SetIgnore(tokenallowance.FieldTokenIdentifier)
		}
		if _, exists := u.create.mutation.TokenCreateID(); exists {
			s.SetIgnore(tokenallowance.FieldTokenCreateID)
		}
		if _, exists := u.create.mutation.PerTransactionCap(); exists {
			s.SetIgnore(tokenallowance.FieldPerTransactionCap)
		}
		if _, exists := u.create.mutation.TotalLimit(); exists {
			s.SetIgnore(tokenallowance.FieldTotalLimit)
		}
		if _, exists := u.create.mutation.RecipientAllowlist(); exists {
			s.SetIgnore(tokenallowance.FieldRecipientAllowlist)
		}
		if _, exists := u.create.mutation.ExpiryTime(); exists {
			s.SetIgnore(tokenallowance.FieldExpiryTime)
		}
		if _, exists := u.create.mutation.Network(); exists {
			s.SetIgnore(tokenallowance.FieldNetwork)
		}
		if _, exists := u.create.mutation.OwnerSignature(); exists {
			s.SetIgnore(tokenallowance.FieldOwnerSignature)
		}
		if _, exists := u.create.mutation.StatementHash(); exists {
			s.SetIgnore(tokenallowance.FieldStatementHash)
		}
		if _, exists := u.create.mutation.Version(); exists {
			s.SetIgnore(tokenallowance.FieldVersion)
		}
		if _, exists := u.create.mutation.OwnerProvidedTimestamp(); exists {
			s.SetIgnore(tokenallowance.FieldOwnerProvidedTimestamp)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TokenAllowance.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TokenAllowanceUpsertOne) Ignore() *TokenAllowanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TokenAllowanceUpsertOne) DoNothing() *TokenAllowanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TokenAllowanceCreate.OnConflict
// documentation for more info.
func (u *TokenAllowanceUpsertOne) Update(set func(*TokenAllowanceUpsert)) *TokenAllowanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TokenAllowanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *TokenAllowanceUpsertOne) SetUpdateTime(v time.Time) *TokenAllowanceUpsertOne {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TokenAllowanceUpsertOne) UpdateUpdateTime() *TokenAllowanceUpsertOne {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetStatus sets the "status" field.
func (u *TokenAllowanceUpsertOne) SetStatus(v schematype.TokenAllowanceStatus) *TokenAllowanceUpsertOne {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TokenAllowanceUpsertOne) UpdateStatus() *TokenAllowanceUpsertOne {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.UpdateStatus()
	})
}

// SetSpentAmount sets the "spent_amount" field.
func (u *TokenAllowanceUpsertOne) SetSpentAmount(v []byte) *TokenAllowanceUpsertOne {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.SetSpentAmount(v)
	})
}

// UpdateSpentAmount sets the "spent_amount" field to the value that was provided on create.
func (u *TokenAllowanceUpsertOne) UpdateSpentAmount() *TokenAllowanceUpsertOne {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.UpdateSpentAmount()
	})
}

// SetOwnerProvidedRevokeTimestamp sets the "owner_provided_revoke_timestamp" field.
func (u *TokenAllowanceUpsertOne) SetOwnerProvidedRevokeTimestamp(v uint64) *TokenAllowanceUpsertOne {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.SetOwnerProvidedRevokeTimestamp(v)
	})
}

// AddOwnerProvidedRevokeTimestamp adds v to the "owner_provided_revoke_timestamp" field.
func (u *TokenAllowanceUpsertOne) AddOwnerProvidedRevokeTimestamp(v uint64) *TokenAllowanceUpsertOne {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.AddOwnerProvidedRevokeTimestamp(v)
	})
}

// UpdateOwnerProvidedRevokeTimestamp sets the "owner_provided_revoke_timestamp" field to the value that was provided on create.
func (u *TokenAllowanceUpsertOne) UpdateOwnerProvidedRevokeTimestamp() *TokenAllowanceUpsertOne {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.UpdateOwnerProvidedRevokeTimestamp()
	})
}

// ClearOwnerProvidedRevokeTimestamp clears the value of the "owner_provided_revoke_timestamp" field.
func (u *TokenAllowanceUpsertOne) ClearOwnerProvidedRevokeTimestamp() *TokenAllowanceUpsertOne {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.ClearOwnerProvidedRevokeTimestamp()
	})
}

// SetRevokeSignature sets the "revoke_signature" field.
func (u *TokenAllowanceUpsertOne) SetRevokeSignature(v []byte) *TokenAllowanceUpsertOne {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.SetRevokeSignature(v)
	})
}

// UpdateRevokeSignature sets the "revoke_signature" field to the value that was provided on create.
func (u *TokenAllowanceUpsertOne) UpdateRevokeSignature() *TokenAllowanceUpsertOne {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.UpdateRevokeSignature()
	})
}

// ClearRevokeSignature clears the value of the "revoke_signature" field.
func (u *TokenAllowanceUpsertOne) ClearRevokeSignature() *TokenAllowanceUpsertOne {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.ClearRevokeSignature()
	})
}

// Exec executes the query.
func (u *TokenAllowanceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TokenAllowanceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TokenAllowanceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TokenAllowanceUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TokenAllowanceUpsertOne.ID is not supported by MySQL driver. Use TokenAllowanceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TokenAllowanceUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TokenAllowanceCreateBulk is the builder for creating many TokenAllowance entities in bulk.
type TokenAllowanceCreateBulk struct {
	config
	err      error
	builders []*TokenAllowanceCreate
	conflict []sql.ConflictOption
}

// Save creates the TokenAllowance entities in the database.
func (tacb *TokenAllowanceCreateBulk) Save(ctx context.Context) ([]*TokenAllowance, error) {
	if tacb.err != nil {
		return nil, tacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tacb.builders))
	nodes := make([]*TokenAllowance, len(tacb.builders))
	mutators := make([]Mutator, len(tacb.builders))
	for i := range tacb.builders {
		func(i int, root context.Context) {
			builder := tacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TokenAllowanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = tacb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tacb *TokenAllowanceCreateBulk) SaveX(ctx context.Context) []*TokenAllowance {
	v, err := tacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tacb *TokenAllowanceCreateBulk) Exec(ctx context.Context) error {
	_, err := tacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tacb *TokenAllowanceCreateBulk) ExecX(ctx context.Context) {
	if err := tacb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TokenAllowance.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TokenAllowanceUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (tacb *TokenAllowanceCreateBulk) OnConflict(opts ...sql.ConflictOption) *TokenAllowanceUpsertBulk {
	tacb.conflict = opts
	return &TokenAllowanceUpsertBulk{
		create: tacb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TokenAllowance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tacb *TokenAllowanceCreateBulk) OnConflictColumns(columns ...string) *TokenAllowanceUpsertBulk {
	tacb.conflict = append(tacb.conflict, sql.ConflictColumns(columns...))
	return &TokenAllowanceUpsertBulk{
		create: tacb,
	}
}

// TokenAllowanceUpsertBulk is the builder for "upsert"-ing
// a bulk of TokenAllowance nodes.
type TokenAllowanceUpsertBulk struct {
	create *TokenAllowanceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TokenAllowance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tokenallowance.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TokenAllowanceUpsertBulk) UpdateNewValues() *TokenAllowanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(tokenallowance.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(tokenallowance.FieldCreateTime)
			}
			if _, exists := b.mutation.AllowanceID(); exists {
				s.SetIgnore(tokenallowance.FieldAllowanceID)
			}
			if _, exists := b.mutation.OwnerPublicKey(); exists {
				s.SetIgnore(tokenallowance.FieldOwnerPublicKey)
			}
			if _, exists := b.mutation.SpenderPublicKey(); exists {
				s.SetIgnore(tokenallowance.FieldSpenderPublicKey)
			}
			if _, exists := b.mutation.TokenIdentifier(); exists {
				s.SetIgnore(tokenallowance.FieldTokenIdentifier)
			}
			if _, exists := b.mutation.TokenCreateID(); exists {
				s.SetIgnore(tokenallowance.FieldTokenCreateID)
			}
			if _, exists := b.mutation.PerTransactionCap(); exists {
				s.SetIgnore(tokenallowance.FieldPerTransactionCap)
			}
			if _, exists := b.mutation.TotalLimit(); exists {
				s.SetIgnore(tokenallowance.FieldTotalLimit)
			}
			if _, exists := b.mutation.RecipientAllowlist(); exists {
				s.SetIgnore(tokenallowance.FieldRecipientAllowlist)
			}
			if _, exists := b.mutation.ExpiryTime(); exists {
				s.SetIgnore(tokenallowance.FieldExpiryTime)
			}
			if _, exists := b.mutation.Network(); exists {
				s.SetIgnore(tokenallowance.FieldNetwork)
			}
			if _, exists := b.mutation.OwnerSignature(); exists {
				s.SetIgnore(tokenallowance.FieldOwnerSignature)
			}
			if _, exists := b.mutation.StatementHash(); exists {
				s.SetIgnore(tokenallowance.FieldStatementHash)
			}
			if _, exists := b.mutation.Version(); exists {
				s.SetIgnore(tokenallowance.FieldVersion)
			}
			if _, exists := b.mutation.OwnerProvidedTimestamp(); exists {
				s.SetIgnore(tokenallowance.FieldOwnerProvidedTimestamp)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TokenAllowance.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TokenAllowanceUpsertBulk) Ignore() *TokenAllowanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TokenAllowanceUpsertBulk) DoNothing() *TokenAllowanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TokenAllowanceCreateBulk.OnConflict
// documentation for more info.
func (u *TokenAllowanceUpsertBulk) Update(set func(*TokenAllowanceUpsert)) *TokenAllowanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TokenAllowanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *TokenAllowanceUpsertBulk) SetUpdateTime(v time.Time) *TokenAllowanceUpsertBulk {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *TokenAllowanceUpsertBulk) UpdateUpdateTime() *TokenAllowanceUpsertBulk {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetStatus sets the "status" field.
func (u *TokenAllowanceUpsertBulk) SetStatus(v schematype.TokenAllowanceStatus) *TokenAllowanceUpsertBulk {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TokenAllowanceUpsertBulk) UpdateStatus() *TokenAllowanceUpsertBulk {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.UpdateStatus()
	})
}

// SetSpentAmount sets the "spent_amount" field.
func (u *TokenAllowanceUpsertBulk) SetSpentAmount(v []byte) *TokenAllowanceUpsertBulk {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.SetSpentAmount(v)
	})
}

// UpdateSpentAmount sets the "spent_amount" field to the value that was provided on create.
func (u *TokenAllowanceUpsertBulk) UpdateSpentAmount() *TokenAllowanceUpsertBulk {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.UpdateSpentAmount()
	})
}

// SetOwnerProvidedRevokeTimestamp sets the "owner_provided_revoke_timestamp" field.
func (u *TokenAllowanceUpsertBulk) SetOwnerProvidedRevokeTimestamp(v uint64) *TokenAllowanceUpsertBulk {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.SetOwnerProvidedRevokeTimestamp(v)
	})
}

// AddOwnerProvidedRevokeTimestamp adds v to the "owner_provided_revoke_timestamp" field.
func (u *TokenAllowanceUpsertBulk) AddOwnerProvidedRevokeTimestamp(v uint64) *TokenAllowanceUpsertBulk {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.AddOwnerProvidedRevokeTimestamp(v)
	})
}

// UpdateOwnerProvidedRevokeTimestamp sets the "owner_provided_revoke_timestamp" field to the value that was provided on create.
func (u *TokenAllowanceUpsertBulk) UpdateOwnerProvidedRevokeTimestamp() *TokenAllowanceUpsertBulk {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.UpdateOwnerProvidedRevokeTimestamp()
	})
}

// ClearOwnerProvidedRevokeTimestamp clears the value of the "owner_provided_revoke_timestamp" field.
func (u *TokenAllowanceUpsertBulk) ClearOwnerProvidedRevokeTimestamp() *TokenAllowanceUpsertBulk {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.ClearOwnerProvidedRevokeTimestamp()
	})
}

// SetRevokeSignature sets the "revoke_signature" field.
func (u *TokenAllowanceUpsertBulk) SetRevokeSignature(v []byte) *TokenAllowanceUpsertBulk {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.SetRevokeSignature(v)
	})
}

// UpdateRevokeSignature sets the "revoke_signature" field to the value that was provided on create.
func (u *TokenAllowanceUpsertBulk) UpdateRevokeSignature() *TokenAllowanceUpsertBulk {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.UpdateRevokeSignature()
	})
}

// ClearRevokeSignature clears the value of the "revoke_signature" field.
func (u *TokenAllowanceUpsertBulk) ClearRevokeSignature() *TokenAllowanceUpsertBulk {
	return u.Update(func(s *TokenAllowanceUpsert) {
		s.ClearRevokeSignature()
	})
}

// Exec executes the query.
func (u *TokenAllowanceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TokenAllowanceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TokenAllowanceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TokenAllowanceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
