// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/common/btcnetwork"
	"github.com/lightsparkdev/spark/common/keys"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
	"github.com/lightsparkdev/spark/so/ent/tokenallowance"
	"github.com/lightsparkdev/spark/so/ent/tokencreate"
)

// TokenAllowance is the model entity for the TokenAllowance schema.
type TokenAllowance struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// The time when the entity was created.
	CreateTime time.Time `json:"create_time,omitempty"`
	// The time when the entity was last updated.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Client-generated identifier for the allowance, shared across all SOs.
	AllowanceID uuid.UUID `json:"allowance_id,omitempty"`
	// Current lifecycle status of the allowance (ACTIVE, REVOKED, EXHAUSTED).
	Status schematype.TokenAllowanceStatus `json:"status,omitempty"`
	// The public key of the token owner that signed this allowance.
	OwnerPublicKey keys.Public `json:"owner_public_key,omitempty"`
	// The public key authorized to spend under this allowance.
	SpenderPublicKey keys.Public `json:"spender_public_key,omitempty"`
	// The identifier of the token this allowance applies to.
	TokenIdentifier []byte `json:"token_identifier,omitempty"`
	// Foreign key referencing the associated TokenCreate record.
	TokenCreateID uuid.UUID `json:"token_create_id,omitempty"`
	// Maximum value a single delegated transaction may move, as a uint128 big-endian.
	PerTransactionCap []byte `json:"per_transaction_cap,omitempty"`
	// Cumulative value the spender may move over the allowance lifetime, as a uint128 big-endian.
	TotalLimit []byte `json:"total_limit,omitempty"`
	// Owner-signed waiver of the per-transaction ceiling (payload v2+). NULL/false means bounded (fail-closed).
	PerTransactionUnlimited bool `json:"per_transaction_unlimited,omitempty"`
	// Owner-signed waiver of the lifetime total ceiling (payload v2+); spent_amount still meters. NULL/false means bounded (fail-closed).
	TotalUnlimited bool `json:"total_unlimited,omitempty"`
	// Value already spent against this allowance, as a uint128 big-endian.
	SpentAmount []byte `json:"spent_amount,omitempty"`
	// Recipient public keys the spender may pay; empty permits any recipient.
	RecipientAllowlist [][]uint8 `json:"recipient_allowlist,omitempty"`
	// Wall-clock time after which the allowance can no longer authorize spends.
	ExpiryTime time.Time `json:"expiry_time,omitempty"`
	// The Bitcoin network this allowance operates on.
	Network btcnetwork.Network `json:"network,omitempty"`
	// The owner's signature over the allowance statement hash.
	OwnerSignature []byte `json:"owner_signature,omitempty"`
	// The canonical statement hash the owner signed to authorize this allowance.
	StatementHash []byte `json:"statement_hash,omitempty"`
	// Monotonic version of the allowance payload the owner signed.
	Version uint64 `json:"version,omitempty"`
	// Wallet-provided timestamp when the allowance was created, in milliseconds.
	OwnerProvidedTimestamp uint64 `json:"owner_provided_timestamp,omitempty"`
	// Consensus flow that prepared this allowance. Commit clears the stamp; rollback is scoped to it so one execution cannot delete another's grant.
	FlowExecutionID *uuid.UUID `json:"flow_execution_id,omitempty"`
	// Wallet-provided timestamp when the allowance was revoked, in milliseconds.
	OwnerProvidedRevokeTimestamp uint64 `json:"owner_provided_revoke_timestamp,omitempty"`
	// The owner's signature over the revoke statement hash, present once revoked.
	RevokeSignature []byte `json:"revoke_signature,omitempty"`
	// Version of the revoke payload the owner signed; persisted so the tombstoned grant can be served back with a verifiable revoke proof.
	RevokeVersion uint64 `json:"revoke_version,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TokenAllowanceQuery when eager-loading is set.
	Edges        TokenAllowanceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TokenAllowanceEdges holds the relations/edges for other nodes in the graph.
type TokenAllowanceEdges struct {
	// Token create contains the token metadata associated with this allowance.
	TokenCreate *TokenCreate `json:"token_create,omitempty"`
	// Metered spends recorded against this allowance.
	TokenAllowanceSpend []*TokenAllowanceSpend `json:"token_allowance_spend,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TokenCreateOrErr returns the TokenCreate value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TokenAllowanceEdges) TokenCreateOrErr() (*TokenCreate, error) {
	if e.TokenCreate != nil {
		return e.TokenCreate, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tokencreate.Label}
	}
	return nil, &NotLoadedError{edge: "token_create"}
}

// TokenAllowanceSpendOrErr returns the TokenAllowanceSpend value or an error if the edge
// was not loaded in eager-loading.
func (e TokenAllowanceEdges) TokenAllowanceSpendOrErr() ([]*TokenAllowanceSpend, error) {
	if e.loadedTypes[1] {
		return e.TokenAllowanceSpend, nil
	}
	return nil, &NotLoadedError{edge: "token_allowance_spend"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TokenAllowance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tokenallowance.FieldFlowExecutionID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case tokenallowance.FieldTokenIdentifier, tokenallowance.FieldPerTransactionCap, tokenallowance.FieldTotalLimit, tokenallowance.FieldSpentAmount, tokenallowance.FieldRecipientAllowlist, tokenallowance.FieldOwnerSignature, tokenallowance.FieldStatementHash, tokenallowance.FieldRevokeSignature:
			values[i] = new([]byte)
		case tokenallowance.FieldNetwork:
			values[i] = new(btcnetwork.Network)
		case tokenallowance.FieldOwnerPublicKey, tokenallowance.FieldSpenderPublicKey:
			values[i] = new(keys.Public)
		case tokenallowance.FieldPerTransactionUnlimited, tokenallowance.FieldTotalUnlimited:
			values[i] = new(sql.NullBool)
		case tokenallowance.FieldVersion, tokenallowance.FieldOwnerProvidedTimestamp, tokenallowance.FieldOwnerProvidedRevokeTimestamp, tokenallowance.FieldRevokeVersion:
			values[i] = new(sql.NullInt64)
		case tokenallowance.FieldStatus:
			values[i] = new(sql.NullString)
		case tokenallowance.FieldCreateTime, tokenallowance.FieldUpdateTime, tokenallowance.FieldExpiryTime:
			values[i] = new(sql.NullTime)
		case tokenallowance.FieldID, tokenallowance.FieldAllowanceID, tokenallowance.FieldTokenCreateID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TokenAllowance fields.
func (ta *TokenAllowance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tokenallowance.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ta.ID = *value
			}
		case tokenallowance.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				ta.CreateTime = value.Time
			}
		case tokenallowance.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				ta.UpdateTime = value.Time
			}
		case tokenallowance.FieldAllowanceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field allowance_id", values[i])
			} else if value != nil {
				ta.AllowanceID = *value
			}
		case tokenallowance.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ta.Status = schematype.TokenAllowanceStatus(value.String)
			}
		case tokenallowance.FieldOwnerPublicKey:
			if value, ok := values[i].(*keys.Public); !ok {
				return fmt.Errorf("unexpected type %T for field owner_public_key", values[i])
			} else if value != nil {
				ta.OwnerPublicKey = *value
			}
		case tokenallowance.FieldSpenderPublicKey:
			if value, ok := values[i].(*keys.Public); !ok {
				return fmt.Errorf("unexpected type %T for field spender_public_key", values[i])
			} else if value != nil {
				ta.SpenderPublicKey = *value
			}
		case tokenallowance.FieldTokenIdentifier:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field token_identifier", values[i])
			} else if value != nil {
				ta.TokenIdentifier = *value
			}
		case tokenallowance.FieldTokenCreateID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field token_create_id", values[i])
			} else if value != nil {
				ta.TokenCreateID = *value
			}
		case tokenallowance.FieldPerTransactionCap:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field per_transaction_cap", values[i])
			} else if value != nil {
				ta.PerTransactionCap = *value
			}
		case tokenallowance.FieldTotalLimit:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field total_limit", values[i])
			} else if value != nil {
				ta.TotalLimit = *value
			}
		case tokenallowance.FieldPerTransactionUnlimited:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field per_transaction_unlimited", values[i])
			} else if value.Valid {
				ta.PerTransactionUnlimited = value.Bool
			}
		case tokenallowance.FieldTotalUnlimited:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field total_unlimited", values[i])
			} else if value.Valid {
				ta.TotalUnlimited = value.Bool
			}
		case tokenallowance.FieldSpentAmount:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field spent_amount", values[i])
			} else if value != nil {
				ta.SpentAmount = *value
			}
		case tokenallowance.FieldRecipientAllowlist:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field recipient_allowlist", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ta.RecipientAllowlist); err != nil {
					return fmt.Errorf("unmarshal field recipient_allowlist: %w", err)
				}
			}
		case tokenallowance.FieldExpiryTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expiry_time", values[i])
			} else if value.Valid {
				ta.ExpiryTime = value.Time
			}
		case tokenallowance.FieldNetwork:
			if value, ok := values[i].(*btcnetwork.Network); !ok {
				return fmt.Errorf("unexpected type %T for field network", values[i])
			} else if value != nil {
				ta.Network = *value
			}
		case tokenallowance.FieldOwnerSignature:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field owner_signature", values[i])
			} else if value != nil {
				ta.OwnerSignature = *value
			}
		case tokenallowance.FieldStatementHash:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field statement_hash", values[i])
			} else if value != nil {
				ta.StatementHash = *value
			}
		case tokenallowance.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				ta.Version = uint64(value.Int64)
			}
		case tokenallowance.FieldOwnerProvidedTimestamp:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_provided_timestamp", values[i])
			} else if value.Valid {
				ta.OwnerProvidedTimestamp = uint64(value.Int64)
			}
		case tokenallowance.FieldFlowExecutionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field flow_execution_id", values[i])
			} else if value.Valid {
				ta.FlowExecutionID = new(uuid.UUID)
				*ta.FlowExecutionID = *value.S.(*uuid.UUID)
			}
		case tokenallowance.FieldOwnerProvidedRevokeTimestamp:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_provided_revoke_timestamp", values[i])
			} else if value.Valid {
				ta.OwnerProvidedRevokeTimestamp = uint64(value.Int64)
			}
		case tokenallowance.FieldRevokeSignature:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field revoke_signature", values[i])
			} else if value != nil {
				ta.RevokeSignature = *value
			}
		case tokenallowance.FieldRevokeVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revoke_version", values[i])
			} else if value.Valid {
				ta.RevokeVersion = uint64(value.Int64)
			}
		default:
			ta.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TokenAllowance.
// This includes values selected through modifiers, order, etc.
func (ta *TokenAllowance) Value(name string) (ent.Value, error) {
	return ta.selectValues.Get(name)
}

// QueryTokenCreate queries the "token_create" edge of the TokenAllowance entity.
func (ta *TokenAllowance) QueryTokenCreate() *TokenCreateQuery {
	return NewTokenAllowanceClient(ta.config).QueryTokenCreate(ta)
}

// QueryTokenAllowanceSpend queries the "token_allowance_spend" edge of the TokenAllowance entity.
func (ta *TokenAllowance) QueryTokenAllowanceSpend() *TokenAllowanceSpendQuery {
	return NewTokenAllowanceClient(ta.config).QueryTokenAllowanceSpend(ta)
}

// Update returns a builder for updating this TokenAllowance.
// Note that you need to call TokenAllowance.Unwrap() before calling this method if this TokenAllowance
// was returned from a transaction, and the transaction was committed or rolled back.
func (ta *TokenAllowance) Update() *TokenAllowanceUpdateOne {
	return NewTokenAllowanceClient(ta.config).UpdateOne(ta)
}

// Unwrap unwraps the TokenAllowance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ta *TokenAllowance) Unwrap() *TokenAllowance {
	_tx, ok := ta.config.driver.(*txDriver)
	if !ok {
		panic("ent: TokenAllowance is not a transactional entity")
	}
	ta.config.driver = _tx.drv
	return ta
}

// String implements the fmt.Stringer.
func (ta *TokenAllowance) String() string {
	var builder strings.Builder
	builder.WriteString("TokenAllowance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ta.ID))
	builder.WriteString("create_time=")
	builder.WriteString(ta.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(ta.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("allowance_id=")
	builder.WriteString(fmt.Sprintf("%v", ta.AllowanceID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", ta.Status))
	builder.WriteString(", ")
	builder.WriteString("owner_public_key=")
	builder.WriteString(fmt.Sprintf("%v", ta.OwnerPublicKey))
	builder.WriteString(", ")
	builder.WriteString("spender_public_key=")
	builder.WriteString(fmt.Sprintf("%v", ta.SpenderPublicKey))
	builder.WriteString(", ")
	builder.WriteString("token_identifier=")
	builder.WriteString(fmt.Sprintf("%v", ta.TokenIdentifier))
	builder.WriteString(", ")
	builder.WriteString("token_create_id=")
	builder.WriteString(fmt.Sprintf("%v", ta.TokenCreateID))
	builder.WriteString(", ")
	builder.WriteString("per_transaction_cap=")
	builder.WriteString(fmt.Sprintf("%v", ta.PerTransactionCap))
	builder.WriteString(", ")
	builder.WriteString("total_limit=")
	builder.WriteString(fmt.Sprintf("%v", ta.TotalLimit))
	builder.WriteString(", ")
	builder.WriteString("per_transaction_unlimited=")
	builder.WriteString(fmt.Sprintf("%v", ta.PerTransactionUnlimited))
	builder.WriteString(", ")
	builder.WriteString("total_unlimited=")
	builder.WriteString(fmt.Sprintf("%v", ta.TotalUnlimited))
	builder.WriteString(", ")
	builder.WriteString("spent_amount=")
	builder.WriteString(fmt.Sprintf("%v", ta.SpentAmount))
	builder.WriteString(", ")
	builder.WriteString("recipient_allowlist=")
	builder.WriteString(fmt.Sprintf("%v", ta.RecipientAllowlist))
	builder.WriteString(", ")
	builder.WriteString("expiry_time=")
	builder.WriteString(ta.ExpiryTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("network=")
	builder.WriteString(fmt.Sprintf("%v", ta.Network))
	builder.WriteString(", ")
	builder.WriteString("owner_signature=")
	builder.WriteString(fmt.Sprintf("%v", ta.OwnerSignature))
	builder.WriteString(", ")
	builder.WriteString("statement_hash=")
	builder.WriteString(fmt.Sprintf("%v", ta.StatementHash))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", ta.Version))
	builder.WriteString(", ")
	builder.WriteString("owner_provided_timestamp=")
	builder.WriteString(fmt.Sprintf("%v", ta.OwnerProvidedTimestamp))
	builder.WriteString(", ")
	if v := ta.FlowExecutionID; v != nil {
		builder.WriteString("flow_execution_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("owner_provided_revoke_timestamp=")
	builder.WriteString(fmt.Sprintf("%v", ta.OwnerProvidedRevokeTimestamp))
	builder.WriteString(", ")
	builder.WriteString("revoke_signature=")
	builder.WriteString(fmt.Sprintf("%v", ta.RevokeSignature))
	builder.WriteString(", ")
	builder.WriteString("revoke_version=")
	builder.WriteString(fmt.Sprintf("%v", ta.RevokeVersion))
	builder.WriteByte(')')
	return builder.String()
}

// TokenAllowances is a parsable slice of TokenAllowance.
type TokenAllowances []*TokenAllowance
