// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/tokenallowance"
	"github.com/lightsparkdev/spark/so/ent/tokenallowancespend"
	"github.com/lightsparkdev/spark/so/ent/tokentransaction"
)

// TokenAllowanceSpendQuery is the builder for querying TokenAllowanceSpend entities.
type TokenAllowanceSpendQuery struct {
	config
	ctx                  *QueryContext
	order                []tokenallowancespend.OrderOption
	inters               []Interceptor
	predicates           []predicate.TokenAllowanceSpend
	withTokenAllowance   *TokenAllowanceQuery
	withTokenTransaction *TokenTransactionQuery
	withFKs              bool
	modifiers            []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TokenAllowanceSpendQuery builder.
func (tasq *TokenAllowanceSpendQuery) Where(ps ...predicate.TokenAllowanceSpend) *TokenAllowanceSpendQuery {
	tasq.predicates = append(tasq.predicates, ps...)
	return tasq
}

// Limit the number of records to be returned by this query.
func (tasq *TokenAllowanceSpendQuery) Limit(limit int) *TokenAllowanceSpendQuery {
	tasq.ctx.Limit = &limit
	return tasq
}

// Offset to start from.
func (tasq *TokenAllowanceSpendQuery) Offset(offset int) *TokenAllowanceSpendQuery {
	tasq.ctx.Offset = &offset
	return tasq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tasq *TokenAllowanceSpendQuery) Unique(unique bool) *TokenAllowanceSpendQuery {
	tasq.ctx.Unique = &unique
	return tasq
}

// Order specifies how the records should be ordered.
func (tasq *TokenAllowanceSpendQuery) Order(o ...tokenallowancespend.OrderOption) *TokenAllowanceSpendQuery {
	tasq.order = append(tasq.order, o...)
	return tasq
}

// QueryTokenAllowance chains the current query on the "token_allowance" edge.
func (tasq *TokenAllowanceSpendQuery) QueryTokenAllowance() *TokenAllowanceQuery {
	query := (&TokenAllowanceClient{config: tasq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tasq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tasq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tokenallowancespend.Table, tokenallowancespend.FieldID, selector),
			sqlgraph.To(tokenallowance.Table, tokenallowance.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tokenallowancespend.TokenAllowanceTable, tokenallowancespend.TokenAllowanceColumn),
		)
		fromU = sqlgraph.SetNeighbors(tasq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTokenTransaction chains the current query on the "token_transaction" edge.
func (tasq *TokenAllowanceSpendQuery) QueryTokenTransaction() *TokenTransactionQuery {
	query := (&TokenTransactionClient{config: tasq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tasq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tasq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tokenallowancespend.Table, tokenallowancespend.FieldID, selector),
			sqlgraph.To(tokentransaction.Table, tokentransaction.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, tokenallowancespend.TokenTransactionTable, tokenallowancespend.TokenTransactionColumn),
		)
		fromU = sqlgraph.SetNeighbors(tasq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TokenAllowanceSpend entity from the query.
// Returns a *NotFoundError when no TokenAllowanceSpend was found.
func (tasq *TokenAllowanceSpendQuery) First(ctx context.Context) (*TokenAllowanceSpend, error) {
	nodes, err := tasq.Limit(1).All(setContextOp(ctx, tasq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tokenallowancespend.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tasq *TokenAllowanceSpendQuery) FirstX(ctx context.Context) *TokenAllowanceSpend {
	node, err := tasq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TokenAllowanceSpend ID from the query.
// Returns a *NotFoundError when no TokenAllowanceSpend ID was found.
func (tasq *TokenAllowanceSpendQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tasq.Limit(1).IDs(setContextOp(ctx, tasq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tokenallowancespend.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tasq *TokenAllowanceSpendQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tasq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TokenAllowanceSpend entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TokenAllowanceSpend entity is found.
// Returns a *NotFoundError when no TokenAllowanceSpend entities are found.
func (tasq *TokenAllowanceSpendQuery) Only(ctx context.Context) (*TokenAllowanceSpend, error) {
	nodes, err := tasq.Limit(2).All(setContextOp(ctx, tasq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tokenallowancespend.Label}
	default:
		return nil, &NotSingularError{tokenallowancespend.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tasq *TokenAllowanceSpendQuery) OnlyX(ctx context.Context) *TokenAllowanceSpend {
	node, err := tasq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TokenAllowanceSpend ID in the query.
// Returns a *NotSingularError when more than one TokenAllowanceSpend ID is found.
// Returns a *NotFoundError when no entities are found.
func (tasq *TokenAllowanceSpendQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tasq.Limit(2).IDs(setContextOp(ctx, tasq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tokenallowancespend.Label}
	default:
		err = &NotSingularError{tokenallowancespend.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tasq *TokenAllowanceSpendQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tasq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TokenAllowanceSpends.
func (tasq *TokenAllowanceSpendQuery) All(ctx context.Context) ([]*TokenAllowanceSpend, error) {
	ctx = setContextOp(ctx, tasq.ctx, ent.OpQueryAll)
	if err := tasq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TokenAllowanceSpend, *TokenAllowanceSpendQuery]()
	return withInterceptors[[]*TokenAllowanceSpend](ctx, tasq, qr, tasq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tasq *TokenAllowanceSpendQuery) AllX(ctx context.Context) []*TokenAllowanceSpend {
	nodes, err := tasq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TokenAllowanceSpend IDs.
func (tasq *TokenAllowanceSpendQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tasq.ctx.Unique == nil && tasq.path != nil {
		tasq.Unique(true)
	}
	ctx = setContextOp(ctx, tasq.ctx, ent.OpQueryIDs)
	if err = tasq.Select(tokenallowancespend.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tasq *TokenAllowanceSpendQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tasq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tasq *TokenAllowanceSpendQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tasq.ctx, ent.OpQueryCount)
	if err := tasq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tasq, querierCount[*TokenAllowanceSpendQuery](), tasq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tasq *TokenAllowanceSpendQuery) CountX(ctx context.Context) int {
	count, err := tasq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tasq *TokenAllowanceSpendQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tasq.ctx, ent.OpQueryExist)
	switch _, err := tasq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tasq *TokenAllowanceSpendQuery) ExistX(ctx context.Context) bool {
	exist, err := tasq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TokenAllowanceSpendQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tasq *TokenAllowanceSpendQuery) Clone() *TokenAllowanceSpendQuery {
	if tasq == nil {
		return nil
	}
	return &TokenAllowanceSpendQuery{
		config:               tasq.config,
		ctx:                  tasq.ctx.Clone(),
		order:                append([]tokenallowancespend.OrderOption{}, tasq.order...),
		inters:               append([]Interceptor{}, tasq.inters...),
		predicates:           append([]predicate.TokenAllowanceSpend{}, tasq.predicates...),
		withTokenAllowance:   tasq.withTokenAllowance.Clone(),
		withTokenTransaction: tasq.withTokenTransaction.Clone(),
		// clone intermediate query.
		sql:       tasq.sql.Clone(),
		path:      tasq.path,
		modifiers: append([]func(*sql.Selector){}, tasq.modifiers...),
	}
}

// WithTokenAllowance tells the query-builder to eager-load the nodes that are connected to
// the "token_allowance" edge. The optional arguments are used to configure the query builder of the edge.
func (tasq *TokenAllowanceSpendQuery) WithTokenAllowance(opts ...func(*TokenAllowanceQuery)) *TokenAllowanceSpendQuery {
	query := (&TokenAllowanceClient{config: tasq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tasq.withTokenAllowance = query
	return tasq
}

// WithTokenTransaction tells the query-builder to eager-load the nodes that are connected to
// the "token_transaction" edge. The optional arguments are used to configure the query builder of the edge.
func (tasq *TokenAllowanceSpendQuery) WithTokenTransaction(opts ...func(*TokenTransactionQuery)) *TokenAllowanceSpendQuery {
	query := (&TokenTransactionClient{config: tasq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tasq.withTokenTransaction = query
	return tasq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TokenAllowanceSpend.Query().
//		GroupBy(tokenallowancespend.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tasq *TokenAllowanceSpendQuery) GroupBy(field string, fields ...string) *TokenAllowanceSpendGroupBy {
	tasq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TokenAllowanceSpendGroupBy{build: tasq}
	grbuild.flds = &tasq.ctx.Fields
	grbuild.label = tokenallowancespend.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.TokenAllowanceSpend.Query().
//		Select(tokenallowancespend.FieldCreateTime).
//		Scan(ctx, &v)
func (tasq *TokenAllowanceSpendQuery) Select(fields ...string) *TokenAllowanceSpendSelect {
	tasq.ctx.Fields = append(tasq.ctx.Fields, fields...)
	sbuild := &TokenAllowanceSpendSelect{TokenAllowanceSpendQuery: tasq}
	sbuild.label = tokenallowancespend.Label
	sbuild.flds, sbuild.scan = &tasq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TokenAllowanceSpendSelect configured with the given aggregations.
func (tasq *TokenAllowanceSpendQuery) Aggregate(fns ...AggregateFunc) *TokenAllowanceSpendSelect {
	return tasq.Select().Aggregate(fns...)
}

func (tasq *TokenAllowanceSpendQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tasq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tasq); err != nil {
				return err
			}
		}
	}
	for _, f := range tasq.ctx.Fields {
		if !tokenallowancespend.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tasq.path != nil {
		prev, err := tasq.path(ctx)
		if err != nil {
			return err
		}
		tasq.sql = prev
	}
	return nil
}

func (tasq *TokenAllowanceSpendQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TokenAllowanceSpend, error) {
	var (
		nodes       = []*TokenAllowanceSpend{}
		withFKs     = tasq.withFKs
		_spec       = tasq.querySpec()
		loadedTypes = [2]bool{
			tasq.withTokenAllowance != nil,
			tasq.withTokenTransaction != nil,
		}
	)
	if tasq.withTokenTransaction != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, tokenallowancespend.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TokenAllowanceSpend).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TokenAllowanceSpend{config: tasq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(tasq.modifiers) > 0 {
		_spec.Modifiers = tasq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tasq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tasq.withTokenAllowance; query != nil {
		if err := tasq.loadTokenAllowance(ctx, query, nodes, nil,
			func(n *TokenAllowanceSpend, e *TokenAllowance) { n.Edges.TokenAllowance = e }); err != nil {
			return nil, err
		}
	}
	if query := tasq.withTokenTransaction; query != nil {
		if err := tasq.loadTokenTransaction(ctx, query, nodes, nil,
			func(n *TokenAllowanceSpend, e *TokenTransaction) { n.Edges.TokenTransaction = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tasq *TokenAllowanceSpendQuery) loadTokenAllowance(ctx context.Context, query *TokenAllowanceQuery, nodes []*TokenAllowanceSpend, init func(*TokenAllowanceSpend), assign func(*TokenAllowanceSpend, *TokenAllowance)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TokenAllowanceSpend)
	for i := range nodes {
		fk := nodes[i].TokenAllowanceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tokenallowance.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "token_allowance_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (tasq *TokenAllowanceSpendQuery) loadTokenTransaction(ctx context.Context, query *TokenTransactionQuery, nodes []*TokenAllowanceSpend, init func(*TokenAllowanceSpend), assign func(*TokenAllowanceSpend, *TokenTransaction)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TokenAllowanceSpend)
	for i := range nodes {
		if nodes[i].token_allowance_spend_token_transaction == nil {
			continue
		}
		fk := *nodes[i].token_allowance_spend_token_transaction
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tokentransaction.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "token_allowance_spend_token_transaction" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tasq *TokenAllowanceSpendQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tasq.querySpec()
	if len(tasq.modifiers) > 0 {
		_spec.Modifiers = tasq.modifiers
	}
	_spec.Node.Columns = tasq.ctx.Fields
	if len(tasq.ctx.Fields) > 0 {
		_spec.Unique = tasq.ctx.Unique != nil && *tasq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tasq.driver, _spec)
}

func (tasq *TokenAllowanceSpendQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tokenallowancespend.Table, tokenallowancespend.Columns, sqlgraph.NewFieldSpec(tokenallowancespend.FieldID, field.TypeUUID))
	_spec.From = tasq.sql
	if unique := tasq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tasq.path != nil {
		_spec.Unique = true
	}
	if fields := tasq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tokenallowancespend.FieldID)
		for i := range fields {
			if fields[i] != tokenallowancespend.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tasq.withTokenAllowance != nil {
			_spec.Node.AddColumnOnce(tokenallowancespend.FieldTokenAllowanceID)
		}
	}
	if ps := tasq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tasq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tasq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tasq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tasq *TokenAllowanceSpendQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tasq.driver.Dialect())
	t1 := builder.Table(tokenallowancespend.Table)
	columns := tasq.ctx.Fields
	if len(columns) == 0 {
		columns = tokenallowancespend.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tasq.sql != nil {
		selector = tasq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tasq.ctx.Unique != nil && *tasq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range tasq.modifiers {
		m(selector)
	}
	for _, p := range tasq.predicates {
		p(selector)
	}
	for _, p := range tasq.order {
		p(selector)
	}
	if offset := tasq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tasq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (tasq *TokenAllowanceSpendQuery) ForUpdate(opts ...sql.LockOption) *TokenAllowanceSpendQuery {
	if tasq.driver.Dialect() == dialect.Postgres {
		tasq.Unique(false)
	}
	tasq.modifiers = append(tasq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return tasq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (tasq *TokenAllowanceSpendQuery) ForShare(opts ...sql.LockOption) *TokenAllowanceSpendQuery {
	if tasq.driver.Dialect() == dialect.Postgres {
		tasq.Unique(false)
	}
	tasq.modifiers = append(tasq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return tasq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tasq *TokenAllowanceSpendQuery) Modify(modifiers ...func(s *sql.Selector)) *TokenAllowanceSpendSelect {
	tasq.modifiers = append(tasq.modifiers, modifiers...)
	return tasq.Select()
}

// TokenAllowanceSpendGroupBy is the group-by builder for TokenAllowanceSpend entities.
type TokenAllowanceSpendGroupBy struct {
	selector
	build *TokenAllowanceSpendQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tasgb *TokenAllowanceSpendGroupBy) Aggregate(fns ...AggregateFunc) *TokenAllowanceSpendGroupBy {
	tasgb.fns = append(tasgb.fns, fns...)
	return tasgb
}

// Scan applies the selector query and scans the result into the given value.
func (tasgb *TokenAllowanceSpendGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tasgb.build.ctx, ent.OpQueryGroupBy)
	if err := tasgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TokenAllowanceSpendQuery, *TokenAllowanceSpendGroupBy](ctx, tasgb.build, tasgb, tasgb.build.inters, v)
}

func (tasgb *TokenAllowanceSpendGroupBy) sqlScan(ctx context.Context, root *TokenAllowanceSpendQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tasgb.fns))
	for _, fn := range tasgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tasgb.flds)+len(tasgb.fns))
		for _, f := range *tasgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tasgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tasgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TokenAllowanceSpendSelect is the builder for selecting fields of TokenAllowanceSpend entities.
type TokenAllowanceSpendSelect struct {
	*TokenAllowanceSpendQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tass *TokenAllowanceSpendSelect) Aggregate(fns ...AggregateFunc) *TokenAllowanceSpendSelect {
	tass.fns = append(tass.fns, fns...)
	return tass
}

// Scan applies the selector query and scans the result into the given value.
func (tass *TokenAllowanceSpendSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tass.ctx, ent.OpQuerySelect)
	if err := tass.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TokenAllowanceSpendQuery, *TokenAllowanceSpendSelect](ctx, tass.TokenAllowanceSpendQuery, tass, tass.inters, v)
}

func (tass *TokenAllowanceSpendSelect) sqlScan(ctx context.Context, root *TokenAllowanceSpendQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tass.fns))
	for _, fn := range tass.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tass.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tass.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tass *TokenAllowanceSpendSelect) Modify(modifiers ...func(s *sql.Selector)) *TokenAllowanceSpendSelect {
	tass.modifiers = append(tass.modifiers, modifiers...)
	return tass
}
