// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/walletsetting"
)

// WalletSettingUpdate is the builder for updating WalletSetting entities.
type WalletSettingUpdate struct {
	config
	hooks     []Hook
	mutation  *WalletSettingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the WalletSettingUpdate builder.
func (wsu *WalletSettingUpdate) Where(ps ...predicate.WalletSetting) *WalletSettingUpdate {
	wsu.mutation.Where(ps...)
	return wsu
}

// SetUpdateTime sets the "update_time" field.
func (wsu *WalletSettingUpdate) SetUpdateTime(t time.Time) *WalletSettingUpdate {
	wsu.mutation.SetUpdateTime(t)
	return wsu
}

// SetPrivateEnabled sets the "private_enabled" field.
func (wsu *WalletSettingUpdate) SetPrivateEnabled(b bool) *WalletSettingUpdate {
	wsu.mutation.SetPrivateEnabled(b)
	return wsu
}

// SetNillablePrivateEnabled sets the "private_enabled" field if the given value is not nil.
func (wsu *WalletSettingUpdate) SetNillablePrivateEnabled(b *bool) *WalletSettingUpdate {
	if b != nil {
		wsu.SetPrivateEnabled(*b)
	}
	return wsu
}

// Mutation returns the WalletSettingMutation object of the builder.
func (wsu *WalletSettingUpdate) Mutation() *WalletSettingMutation {
	return wsu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wsu *WalletSettingUpdate) Save(ctx context.Context) (int, error) {
	wsu.defaults()
	return withHooks(ctx, wsu.sqlSave, wsu.mutation, wsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wsu *WalletSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := wsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wsu *WalletSettingUpdate) Exec(ctx context.Context) error {
	_, err := wsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wsu *WalletSettingUpdate) ExecX(ctx context.Context) {
	if err := wsu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wsu *WalletSettingUpdate) defaults() {
	if _, ok := wsu.mutation.UpdateTime(); !ok {
		v := walletsetting.UpdateDefaultUpdateTime()
		wsu.mutation.SetUpdateTime(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (wsu *WalletSettingUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WalletSettingUpdate {
	wsu.modifiers = append(wsu.modifiers, modifiers...)
	return wsu
}

func (wsu *WalletSettingUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(walletsetting.Table, walletsetting.Columns, sqlgraph.NewFieldSpec(walletsetting.FieldID, field.TypeUUID))
	if ps := wsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wsu.mutation.UpdateTime(); ok {
		_spec.SetField(walletsetting.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := wsu.mutation.PrivateEnabled(); ok {
		_spec.SetField(walletsetting.FieldPrivateEnabled, field.TypeBool, value)
	}
	_spec.AddModifiers(wsu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, wsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{walletsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wsu.mutation.done = true
	return n, nil
}

// WalletSettingUpdateOne is the builder for updating a single WalletSetting entity.
type WalletSettingUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *WalletSettingMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (wsuo *WalletSettingUpdateOne) SetUpdateTime(t time.Time) *WalletSettingUpdateOne {
	wsuo.mutation.SetUpdateTime(t)
	return wsuo
}

// SetPrivateEnabled sets the "private_enabled" field.
func (wsuo *WalletSettingUpdateOne) SetPrivateEnabled(b bool) *WalletSettingUpdateOne {
	wsuo.mutation.SetPrivateEnabled(b)
	return wsuo
}

// SetNillablePrivateEnabled sets the "private_enabled" field if the given value is not nil.
func (wsuo *WalletSettingUpdateOne) SetNillablePrivateEnabled(b *bool) *WalletSettingUpdateOne {
	if b != nil {
		wsuo.SetPrivateEnabled(*b)
	}
	return wsuo
}

// Mutation returns the WalletSettingMutation object of the builder.
func (wsuo *WalletSettingUpdateOne) Mutation() *WalletSettingMutation {
	return wsuo.mutation
}

// Where appends a list predicates to the WalletSettingUpdate builder.
func (wsuo *WalletSettingUpdateOne) Where(ps ...predicate.WalletSetting) *WalletSettingUpdateOne {
	wsuo.mutation.Where(ps...)
	return wsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wsuo *WalletSettingUpdateOne) Select(field string, fields ...string) *WalletSettingUpdateOne {
	wsuo.fields = append([]string{field}, fields...)
	return wsuo
}

// Save executes the query and returns the updated WalletSetting entity.
func (wsuo *WalletSettingUpdateOne) Save(ctx context.Context) (*WalletSetting, error) {
	wsuo.defaults()
	return withHooks(ctx, wsuo.sqlSave, wsuo.mutation, wsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wsuo *WalletSettingUpdateOne) SaveX(ctx context.Context) *WalletSetting {
	node, err := wsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wsuo *WalletSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := wsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wsuo *WalletSettingUpdateOne) ExecX(ctx context.Context) {
	if err := wsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wsuo *WalletSettingUpdateOne) defaults() {
	if _, ok := wsuo.mutation.UpdateTime(); !ok {
		v := walletsetting.UpdateDefaultUpdateTime()
		wsuo.mutation.SetUpdateTime(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (wsuo *WalletSettingUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WalletSettingUpdateOne {
	wsuo.modifiers = append(wsuo.modifiers, modifiers...)
	return wsuo
}

func (wsuo *WalletSettingUpdateOne) sqlSave(ctx context.Context) (_node *WalletSetting, err error) {
	_spec := sqlgraph.NewUpdateSpec(walletsetting.Table, walletsetting.Columns, sqlgraph.NewFieldSpec(walletsetting.FieldID, field.TypeUUID))
	id, ok := wsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WalletSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, walletsetting.FieldID)
		for _, f := range fields {
			if !walletsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != walletsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wsuo.mutation.UpdateTime(); ok {
		_spec.SetField(walletsetting.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := wsuo.mutation.PrivateEnabled(); ok {
		_spec.SetField(walletsetting.FieldPrivateEnabled, field.TypeBool, value)
	}
	_spec.AddModifiers(wsuo.modifiers...)
	_node = &WalletSetting{config: wsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{walletsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wsuo.mutation.done = true
	return _node, nil
}
