package schema

import (
	"context"
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/lightsparkdev/spark/common"
	bitcointransaction "github.com/lightsparkdev/spark/common/bitcoin_transaction"
	gen "github.com/lightsparkdev/spark/so/ent"
	"github.com/lightsparkdev/spark/so/ent/hook"
	st "github.com/lightsparkdev/spark/so/ent/schema/schematype"
)

// TransferLeaf is the junction schema between Transfer and TreeNode.
type TransferLeaf struct {
	ent.Schema
}

// Mixin is the mixin for the TransferLeaf table.
func (TransferLeaf) Mixin() []ent.Mixin {
	return []ent.Mixin{
		BaseMixin{},
	}
}

// Fields are the fields for the TransferLeaf table.
func (TransferLeaf) Fields() []ent.Field {
	return []ent.Field{
		field.Bytes("secret_cipher").Optional(),
		field.Bytes("signature").Optional(),
		field.Bytes("previous_refund_tx").NotEmpty().Immutable(),
		field.Bytes("previous_direct_refund_tx").Optional().Immutable(),
		field.Bytes("previous_direct_from_cpfp_refund_tx").Optional().Immutable(),
		field.Bytes("intermediate_refund_tx").NotEmpty(),
		field.Bytes("intermediate_direct_refund_tx").Optional(),
		field.Bytes("intermediate_direct_from_cpfp_refund_tx").Optional(),
		field.Bytes("intermediate_refund_txid").Optional().GoType(st.TxID{}).Comment("Valid transaction ID of the stored intermediate refund transaction. Generated by hooks from intermediate_refund_tx."),
		field.Bytes("intermediate_direct_refund_txid").Optional().GoType(st.TxID{}).Comment("Valid transaction ID of the stored intermediate direct refund transaction. Generated by hooks from intermediate_direct_refund_tx."),
		field.Bytes("intermediate_direct_from_cpfp_refund_txid").Optional().GoType(st.TxID{}).Comment("Valid transaction ID of the stored intermediate direct from CPFP refund transaction. Generated by hooks from intermediate_direct_from_cpfp_refund_tx."),
		field.Uint64("intermediate_refund_timelock").Optional().Comment("Timelock value extracted from intermediate_refund_tx. Generated by hooks."),
		field.Uint64("intermediate_direct_refund_timelock").Optional().Comment("Timelock value extracted from intermediate_direct_refund_tx. Generated by hooks."),
		field.Uint64("intermediate_direct_from_cpfp_refund_timelock").Optional().Comment("Timelock value extracted from intermediate_direct_from_cpfp_refund_tx. Generated by hooks."),
		field.Bytes("key_tweak").Optional(),
		field.Bytes("sender_key_tweak_proof").Optional(),
		field.Bytes("receiver_key_tweak").Optional(),
	}
}

// Edges are the edges for the TransferLeaf table.
func (TransferLeaf) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("transfer", Transfer.Type).
			Unique().
			Immutable().
			Required(),
		edge.To("leaf", TreeNode.Type).
			Unique().
			Immutable().
			Required(),
	}
}

// Indexes are the indexes for the TransferLeaf table.
func (TransferLeaf) Indexes() []ent.Index {
	return []ent.Index{
		index.Edges("transfer"),
		index.Edges("leaf"),

		index.Fields("intermediate_refund_txid").Annotations(
			entsql.IndexWhere("intermediate_refund_txid is not null"),
		),
		index.Fields("intermediate_direct_refund_txid").Annotations(
			entsql.IndexWhere("intermediate_direct_refund_txid is not null"),
		),
		index.Fields("intermediate_direct_from_cpfp_refund_txid").Annotations(
			entsql.IndexWhere("intermediate_direct_from_cpfp_refund_txid is not null"),
		),
		index.Fields("intermediate_refund_timelock").Annotations(
			entsql.IndexWhere("intermediate_refund_timelock is not null"),
		),
		index.Fields("intermediate_direct_refund_timelock").Annotations(
			entsql.IndexWhere("intermediate_direct_refund_timelock is not null"),
		),
		index.Fields("intermediate_direct_from_cpfp_refund_timelock").Annotations(
			entsql.IndexWhere("intermediate_direct_from_cpfp_refund_timelock is not null"),
		),
	}
}

func (TransferLeaf) Hooks() []ent.Hook {
	return []ent.Hook{
		// Define helper hooks that will populate TXIDs for the transactions in the mutation.
		// Clearing a field will also clear a corresponding TXID.
		// Be mindful that updates on transactions are slower because the DB indexes on TXIDs are also updated.
		// The first hook handles single entity updates and the second hook handles creations.
		hook.On(
			func(next ent.Mutator) ent.Mutator {
				return hook.TransferLeafFunc(func(ctx context.Context, m *gen.TransferLeafMutation) (ent.Value, error) {
					err := checkTransferLeafTxids(m)
					if err != nil {
						return nil, err
					}

					leafIdUuid, _ := m.ID()
					leafId := leafIdUuid.String()

					// Handling an update on a field
					// intermediate_refund_tx is NotEmpty() so it cannot be cleared, only updated
					if intermediateRefundTxBytes, ok := m.IntermediateRefundTx(); ok {
						intermediateRefundTx, err := common.TxFromRawTxBytes(intermediateRefundTxBytes)
						if err != nil {
							return nil, fmt.Errorf("failed to parse intermediate_refund_tx for transfer leaf %s: %w", leafId, err)
						}
						intermediateRefundTxid := intermediateRefundTx.TxHash()
						m.SetIntermediateRefundTxid(st.NewTxID(intermediateRefundTxid))

						timelock, err := bitcointransaction.GetAndValidateUserTimelock(intermediateRefundTxBytes)
						if err != nil {
							return nil, fmt.Errorf("failed to parse intermediate_refund_tx timelock for transfer leaf %s: %w", leafId, err)
						}
						m.SetIntermediateRefundTimelock(uint64(timelock))
					}

					if m.IntermediateDirectRefundTxCleared() {
						m.ClearIntermediateDirectRefundTxid()
						m.ClearIntermediateDirectRefundTimelock()
					} else {
						if intermediateDirectRefundTxBytes, ok := m.IntermediateDirectRefundTx(); ok {
							if intermediateDirectRefundTxBytes == nil {
								m.ClearIntermediateDirectRefundTxid()
								m.ClearIntermediateDirectRefundTimelock()
							} else {
								intermediateDirectRefundTx, err := common.TxFromRawTxBytes(intermediateDirectRefundTxBytes)
								if err != nil {
									return nil, fmt.Errorf("failed to parse intermediate_direct_refund_tx for transfer leaf %s: %w", leafId, err)
								}
								intermediateDirectRefundTxid := intermediateDirectRefundTx.TxHash()
								m.SetIntermediateDirectRefundTxid(st.NewTxID(intermediateDirectRefundTxid))

								timelock, err := bitcointransaction.GetAndValidateUserTimelock(intermediateDirectRefundTxBytes)
								if err != nil {
									return nil, fmt.Errorf("failed to parse intermediate_direct_refund_tx timelock for transfer leaf %s: %w", leafId, err)
								}
								m.SetIntermediateDirectRefundTimelock(uint64(timelock))
							}
						}
					}

					if m.IntermediateDirectFromCpfpRefundTxCleared() {
						m.ClearIntermediateDirectFromCpfpRefundTxid()
						m.ClearIntermediateDirectFromCpfpRefundTimelock()
					} else {
						if intermediateDirectFromCpfpRefundTxBytes, ok := m.IntermediateDirectFromCpfpRefundTx(); ok {
							if intermediateDirectFromCpfpRefundTxBytes == nil {
								m.ClearIntermediateDirectFromCpfpRefundTxid()
								m.ClearIntermediateDirectFromCpfpRefundTimelock()
							} else {
								intermediateDirectFromCpfpRefundTx, err := common.TxFromRawTxBytes(intermediateDirectFromCpfpRefundTxBytes)
								if err != nil {
									return nil, fmt.Errorf("failed to parse intermediate_direct_from_cpfp_refund_tx for transfer leaf %s: %w", leafId, err)
								}
								intermediateDirectFromCpfpRefundTxid := intermediateDirectFromCpfpRefundTx.TxHash()
								m.SetIntermediateDirectFromCpfpRefundTxid(st.NewTxID(intermediateDirectFromCpfpRefundTxid))

								timelock, err := bitcointransaction.GetAndValidateUserTimelock(intermediateDirectFromCpfpRefundTxBytes)
								if err != nil {
									return nil, fmt.Errorf("failed to parse intermediate_direct_from_cpfp_refund_tx timelock for transfer leaf %s: %w", leafId, err)
								}
								m.SetIntermediateDirectFromCpfpRefundTimelock(uint64(timelock))
							}
						}
					}
					return next.Mutate(ctx, m)
				})
			},
			ent.OpUpdateOne|ent.OpUpdate,
		),
		// Create ent hook
		hook.On(
			func(next ent.Mutator) ent.Mutator {
				return hook.TransferLeafFunc(func(ctx context.Context, m *gen.TransferLeafMutation) (ent.Value, error) {
					err := checkTransferLeafTxids(m)
					if err != nil {
						return nil, err
					}

					leafIdUuid, _ := m.ID()
					leafId := leafIdUuid.String()

					intermediateRefundTxBytes, _ := m.IntermediateRefundTx()
					intermediateRefundTx, err := common.TxFromRawTxBytes(intermediateRefundTxBytes)
					if err != nil {
						return nil, fmt.Errorf("failed to parse intermediate_refund_tx for transfer leaf %s: %w", leafId, err)
					}
					intermediateRefundTxid := intermediateRefundTx.TxHash()
					m.SetIntermediateRefundTxid(st.NewTxID(intermediateRefundTxid))

					timelock, err := bitcointransaction.GetAndValidateUserTimelock(intermediateRefundTxBytes)
					if err != nil {
						return nil, fmt.Errorf("failed to parse intermediate_refund_tx timelock for transfer leaf %s: %w", leafId, err)
					}
					m.SetIntermediateRefundTimelock(uint64(timelock))

					intermediateDirectRefundTxBytes, _ := m.IntermediateDirectRefundTx()
					if intermediateDirectRefundTxBytes != nil {
						intermediateDirectRefundTx, err := common.TxFromRawTxBytes(intermediateDirectRefundTxBytes)
						if err != nil {
							return nil, fmt.Errorf("failed to parse intermediate_direct_refund_tx for transfer leaf %s: %w", leafId, err)
						}
						intermediateDirectRefundTxid := intermediateDirectRefundTx.TxHash()
						m.SetIntermediateDirectRefundTxid(st.NewTxID(intermediateDirectRefundTxid))

						timelock, err := bitcointransaction.GetAndValidateUserTimelock(intermediateDirectRefundTxBytes)
						if err != nil {
							return nil, fmt.Errorf("failed to parse intermediate_direct_refund_tx timelock for transfer leaf %s: %w", leafId, err)
						}
						m.SetIntermediateDirectRefundTimelock(uint64(timelock))
					}

					intermediateDirectFromCpfpRefundTxBytes, _ := m.IntermediateDirectFromCpfpRefundTx()
					if intermediateDirectFromCpfpRefundTxBytes != nil {
						intermediateDirectFromCpfpRefundTx, err := common.TxFromRawTxBytes(intermediateDirectFromCpfpRefundTxBytes)
						if err != nil {
							return nil, fmt.Errorf("failed to parse intermediate_direct_from_cpfp_refund_tx for transfer leaf %s: %w", leafId, err)
						}
						intermediateDirectFromCpfpRefundTxid := intermediateDirectFromCpfpRefundTx.TxHash()
						m.SetIntermediateDirectFromCpfpRefundTxid(st.NewTxID(intermediateDirectFromCpfpRefundTxid))

						timelock, err := bitcointransaction.GetAndValidateUserTimelock(intermediateDirectFromCpfpRefundTxBytes)
						if err != nil {
							return nil, fmt.Errorf("failed to parse intermediate_direct_from_cpfp_refund_tx timelock for transfer leaf %s: %w", leafId, err)
						}
						m.SetIntermediateDirectFromCpfpRefundTimelock(uint64(timelock))
					}
					return next.Mutate(ctx, m)
				})
			},
			ent.OpCreate,
		),
	}
}

// Checks if the txids and timelocks are set directly.
// This is not allowed because the txids and timelocks are generated by hooks from the transactions.
func checkTransferLeafTxids(m *gen.TransferLeafMutation) error {
	if _, ok := m.IntermediateRefundTxid(); ok {
		return fmt.Errorf("intermediate_refund_txid is not allowed to be set directly")
	}
	if _, ok := m.IntermediateDirectRefundTxid(); ok {
		return fmt.Errorf("intermediate_direct_refund_txid is not allowed to be set directly")
	}
	if _, ok := m.IntermediateDirectFromCpfpRefundTxid(); ok {
		return fmt.Errorf("intermediate_direct_from_cpfp_refund_txid is not allowed to be set directly")
	}
	if _, ok := m.IntermediateRefundTimelock(); ok {
		return fmt.Errorf("intermediate_refund_timelock is not allowed to be set directly")
	}
	if _, ok := m.IntermediateDirectRefundTimelock(); ok {
		return fmt.Errorf("intermediate_direct_refund_timelock is not allowed to be set directly")
	}
	if _, ok := m.IntermediateDirectFromCpfpRefundTimelock(); ok {
		return fmt.Errorf("intermediate_direct_from_cpfp_refund_timelock is not allowed to be set directly")
	}
	return nil
}
