// Code generated by ent, DO NOT EDIT.

package tokenallowancespend

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
)

const (
	// Label holds the string label denoting the tokenallowancespend type in the database.
	Label = "token_allowance_spend"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldTokenAllowanceID holds the string denoting the token_allowance_id field in the database.
	FieldTokenAllowanceID = "token_allowance_id"
	// FieldMeteredAmount holds the string denoting the metered_amount field in the database.
	FieldMeteredAmount = "metered_amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeTokenAllowance holds the string denoting the token_allowance edge name in mutations.
	EdgeTokenAllowance = "token_allowance"
	// EdgeTokenTransaction holds the string denoting the token_transaction edge name in mutations.
	EdgeTokenTransaction = "token_transaction"
	// Table holds the table name of the tokenallowancespend in the database.
	Table = "token_allowance_spends"
	// TokenAllowanceTable is the table that holds the token_allowance relation/edge.
	TokenAllowanceTable = "token_allowance_spends"
	// TokenAllowanceInverseTable is the table name for the TokenAllowance entity.
	// It exists in this package in order to avoid circular dependency with the "tokenallowance" package.
	TokenAllowanceInverseTable = "token_allowances"
	// TokenAllowanceColumn is the table column denoting the token_allowance relation/edge.
	TokenAllowanceColumn = "token_allowance_id"
	// TokenTransactionTable is the table that holds the token_transaction relation/edge.
	TokenTransactionTable = "token_allowance_spends"
	// TokenTransactionInverseTable is the table name for the TokenTransaction entity.
	// It exists in this package in order to avoid circular dependency with the "tokentransaction" package.
	TokenTransactionInverseTable = "token_transactions"
	// TokenTransactionColumn is the table column denoting the token_transaction relation/edge.
	TokenTransactionColumn = "token_allowance_spend_token_transaction"
)

// Columns holds all SQL columns for tokenallowancespend fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldTokenAllowanceID,
	FieldMeteredAmount,
	FieldStatus,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "token_allowance_spends"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"token_allowance_spend_token_transaction",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

const DefaultStatus schematype.TokenAllowanceSpendStatus = "RESERVED"

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s schematype.TokenAllowanceSpendStatus) error {
	switch s {
	case "RESERVED", "RELEASED":
		return nil
	default:
		return fmt.Errorf("tokenallowancespend: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the TokenAllowanceSpend queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByTokenAllowanceID orders the results by the token_allowance_id field.
func ByTokenAllowanceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenAllowanceID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTokenAllowanceField orders the results by token_allowance field.
func ByTokenAllowanceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTokenAllowanceStep(), sql.OrderByField(field, opts...))
	}
}

// ByTokenTransactionField orders the results by token_transaction field.
func ByTokenTransactionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTokenTransactionStep(), sql.OrderByField(field, opts...))
	}
}
func newTokenAllowanceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TokenAllowanceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TokenAllowanceTable, TokenAllowanceColumn),
	)
}
func newTokenTransactionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TokenTransactionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, TokenTransactionTable, TokenTransactionColumn),
	)
}
