// Code generated by ent, DO NOT EDIT.

package tokenissuance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark-go/so/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldEQ(FieldUpdateTime, v))
}

// IssuerPublicKey applies equality check predicate on the "issuer_public_key" field. It's identical to IssuerPublicKeyEQ.
func IssuerPublicKey(v []byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldEQ(FieldIssuerPublicKey, v))
}

// IssuerSignature applies equality check predicate on the "issuer_signature" field. It's identical to IssuerSignatureEQ.
func IssuerSignature(v []byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldEQ(FieldIssuerSignature, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldLTE(FieldUpdateTime, v))
}

// IssuerPublicKeyEQ applies the EQ predicate on the "issuer_public_key" field.
func IssuerPublicKeyEQ(v []byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldEQ(FieldIssuerPublicKey, v))
}

// IssuerPublicKeyNEQ applies the NEQ predicate on the "issuer_public_key" field.
func IssuerPublicKeyNEQ(v []byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldNEQ(FieldIssuerPublicKey, v))
}

// IssuerPublicKeyIn applies the In predicate on the "issuer_public_key" field.
func IssuerPublicKeyIn(vs ...[]byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldIn(FieldIssuerPublicKey, vs...))
}

// IssuerPublicKeyNotIn applies the NotIn predicate on the "issuer_public_key" field.
func IssuerPublicKeyNotIn(vs ...[]byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldNotIn(FieldIssuerPublicKey, vs...))
}

// IssuerPublicKeyGT applies the GT predicate on the "issuer_public_key" field.
func IssuerPublicKeyGT(v []byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldGT(FieldIssuerPublicKey, v))
}

// IssuerPublicKeyGTE applies the GTE predicate on the "issuer_public_key" field.
func IssuerPublicKeyGTE(v []byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldGTE(FieldIssuerPublicKey, v))
}

// IssuerPublicKeyLT applies the LT predicate on the "issuer_public_key" field.
func IssuerPublicKeyLT(v []byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldLT(FieldIssuerPublicKey, v))
}

// IssuerPublicKeyLTE applies the LTE predicate on the "issuer_public_key" field.
func IssuerPublicKeyLTE(v []byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldLTE(FieldIssuerPublicKey, v))
}

// IssuerSignatureEQ applies the EQ predicate on the "issuer_signature" field.
func IssuerSignatureEQ(v []byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldEQ(FieldIssuerSignature, v))
}

// IssuerSignatureNEQ applies the NEQ predicate on the "issuer_signature" field.
func IssuerSignatureNEQ(v []byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldNEQ(FieldIssuerSignature, v))
}

// IssuerSignatureIn applies the In predicate on the "issuer_signature" field.
func IssuerSignatureIn(vs ...[]byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldIn(FieldIssuerSignature, vs...))
}

// IssuerSignatureNotIn applies the NotIn predicate on the "issuer_signature" field.
func IssuerSignatureNotIn(vs ...[]byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldNotIn(FieldIssuerSignature, vs...))
}

// IssuerSignatureGT applies the GT predicate on the "issuer_signature" field.
func IssuerSignatureGT(v []byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldGT(FieldIssuerSignature, v))
}

// IssuerSignatureGTE applies the GTE predicate on the "issuer_signature" field.
func IssuerSignatureGTE(v []byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldGTE(FieldIssuerSignature, v))
}

// IssuerSignatureLT applies the LT predicate on the "issuer_signature" field.
func IssuerSignatureLT(v []byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldLT(FieldIssuerSignature, v))
}

// IssuerSignatureLTE applies the LTE predicate on the "issuer_signature" field.
func IssuerSignatureLTE(v []byte) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.FieldLTE(FieldIssuerSignature, v))
}

// HasTokenTransactionReceipt applies the HasEdge predicate on the "token_transaction_receipt" edge.
func HasTokenTransactionReceipt() predicate.TokenIssuance {
	return predicate.TokenIssuance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, TokenTransactionReceiptTable, TokenTransactionReceiptColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTokenTransactionReceiptWith applies the HasEdge predicate on the "token_transaction_receipt" edge with a given conditions (other predicates).
func HasTokenTransactionReceiptWith(preds ...predicate.TokenTransactionReceipt) predicate.TokenIssuance {
	return predicate.TokenIssuance(func(s *sql.Selector) {
		step := newTokenTransactionReceiptStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TokenIssuance) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TokenIssuance) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TokenIssuance) predicate.TokenIssuance {
	return predicate.TokenIssuance(sql.NotPredicates(p))
}
