// Code generated by ent, DO NOT EDIT.

package preimagesharepartner

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the preimagesharepartner type in the database.
	Label = "preimage_share_partner"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// EdgePartner holds the string denoting the partner edge name in mutations.
	EdgePartner = "partner"
	// EdgePreimageShare holds the string denoting the preimage_share edge name in mutations.
	EdgePreimageShare = "preimage_share"
	// Table holds the table name of the preimagesharepartner in the database.
	Table = "preimage_share_partners"
	// PartnerTable is the table that holds the partner relation/edge.
	PartnerTable = "preimage_share_partners"
	// PartnerInverseTable is the table name for the Partner entity.
	// It exists in this package in order to avoid circular dependency with the "partner" package.
	PartnerInverseTable = "partners"
	// PartnerColumn is the table column denoting the partner relation/edge.
	PartnerColumn = "preimage_share_partner_partner"
	// PreimageShareTable is the table that holds the preimage_share relation/edge.
	PreimageShareTable = "preimage_share_partners"
	// PreimageShareInverseTable is the table name for the PreimageShare entity.
	// It exists in this package in order to avoid circular dependency with the "preimageshare" package.
	PreimageShareInverseTable = "preimage_shares"
	// PreimageShareColumn is the table column denoting the preimage_share relation/edge.
	PreimageShareColumn = "preimage_share_partner_preimage_share"
)

// Columns holds all SQL columns for preimagesharepartner fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "preimage_share_partners"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"preimage_share_partner_partner",
	"preimage_share_partner_preimage_share",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the PreimageSharePartner queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByPartnerField orders the results by partner field.
func ByPartnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPartnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByPreimageShareField orders the results by preimage_share field.
func ByPreimageShareField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPreimageShareStep(), sql.OrderByField(field, opts...))
	}
}
func newPartnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PartnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, PartnerTable, PartnerColumn),
	)
}
func newPreimageShareStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PreimageShareInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, PreimageShareTable, PreimageShareColumn),
	)
}
