// Code generated by ent, DO NOT EDIT.

package delegationgrantspender

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/lightsparkdev/spark/common/keys"
	"github.com/lightsparkdev/spark/so/ent/predicate"
	"github.com/lightsparkdev/spark/so/ent/schema/schematype"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldUpdateTime, v))
}

// SpenderIdentityPubkey applies equality check predicate on the "spender_identity_pubkey" field. It's identical to SpenderIdentityPubkeyEQ.
func SpenderIdentityPubkey(v keys.Public) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldSpenderIdentityPubkey, v))
}

// PerTxCapSats applies equality check predicate on the "per_tx_cap_sats" field. It's identical to PerTxCapSatsEQ.
func PerTxCapSats(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldPerTxCapSats, v))
}

// RollingLimitSats applies equality check predicate on the "rolling_limit_sats" field. It's identical to RollingLimitSatsEQ.
func RollingLimitSats(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldRollingLimitSats, v))
}

// RollingWindowSeconds applies equality check predicate on the "rolling_window_seconds" field. It's identical to RollingWindowSecondsEQ.
func RollingWindowSeconds(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldRollingWindowSeconds, v))
}

// PerTxUnlimited applies equality check predicate on the "per_tx_unlimited" field. It's identical to PerTxUnlimitedEQ.
func PerTxUnlimited(v bool) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldPerTxUnlimited, v))
}

// RollingUnlimited applies equality check predicate on the "rolling_unlimited" field. It's identical to RollingUnlimitedEQ.
func RollingUnlimited(v bool) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldRollingUnlimited, v))
}

// SpentSats applies equality check predicate on the "spent_sats" field. It's identical to SpentSatsEQ.
func SpentSats(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldSpentSats, v))
}

// WindowStart applies equality check predicate on the "window_start" field. It's identical to WindowStartEQ.
func WindowStart(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldWindowStart, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldVersion, v))
}

// OwnerSignature applies equality check predicate on the "owner_signature" field. It's identical to OwnerSignatureEQ.
func OwnerSignature(v []byte) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldOwnerSignature, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLTE(FieldUpdateTime, v))
}

// SpenderIdentityPubkeyEQ applies the EQ predicate on the "spender_identity_pubkey" field.
func SpenderIdentityPubkeyEQ(v keys.Public) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldSpenderIdentityPubkey, v))
}

// SpenderIdentityPubkeyNEQ applies the NEQ predicate on the "spender_identity_pubkey" field.
func SpenderIdentityPubkeyNEQ(v keys.Public) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNEQ(FieldSpenderIdentityPubkey, v))
}

// SpenderIdentityPubkeyIn applies the In predicate on the "spender_identity_pubkey" field.
func SpenderIdentityPubkeyIn(vs ...keys.Public) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldIn(FieldSpenderIdentityPubkey, vs...))
}

// SpenderIdentityPubkeyNotIn applies the NotIn predicate on the "spender_identity_pubkey" field.
func SpenderIdentityPubkeyNotIn(vs ...keys.Public) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNotIn(FieldSpenderIdentityPubkey, vs...))
}

// SpenderIdentityPubkeyGT applies the GT predicate on the "spender_identity_pubkey" field.
func SpenderIdentityPubkeyGT(v keys.Public) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGT(FieldSpenderIdentityPubkey, v))
}

// SpenderIdentityPubkeyGTE applies the GTE predicate on the "spender_identity_pubkey" field.
func SpenderIdentityPubkeyGTE(v keys.Public) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGTE(FieldSpenderIdentityPubkey, v))
}

// SpenderIdentityPubkeyLT applies the LT predicate on the "spender_identity_pubkey" field.
func SpenderIdentityPubkeyLT(v keys.Public) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLT(FieldSpenderIdentityPubkey, v))
}

// SpenderIdentityPubkeyLTE applies the LTE predicate on the "spender_identity_pubkey" field.
func SpenderIdentityPubkeyLTE(v keys.Public) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLTE(FieldSpenderIdentityPubkey, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v schematype.DelegationStatus) predicate.DelegationGrantSpender {
	vc := v
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v schematype.DelegationStatus) predicate.DelegationGrantSpender {
	vc := v
	return predicate.DelegationGrantSpender(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...schematype.DelegationStatus) predicate.DelegationGrantSpender {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.DelegationGrantSpender(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...schematype.DelegationStatus) predicate.DelegationGrantSpender {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.DelegationGrantSpender(sql.FieldNotIn(FieldStatus, v...))
}

// PerTxCapSatsEQ applies the EQ predicate on the "per_tx_cap_sats" field.
func PerTxCapSatsEQ(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldPerTxCapSats, v))
}

// PerTxCapSatsNEQ applies the NEQ predicate on the "per_tx_cap_sats" field.
func PerTxCapSatsNEQ(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNEQ(FieldPerTxCapSats, v))
}

// PerTxCapSatsIn applies the In predicate on the "per_tx_cap_sats" field.
func PerTxCapSatsIn(vs ...uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldIn(FieldPerTxCapSats, vs...))
}

// PerTxCapSatsNotIn applies the NotIn predicate on the "per_tx_cap_sats" field.
func PerTxCapSatsNotIn(vs ...uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNotIn(FieldPerTxCapSats, vs...))
}

// PerTxCapSatsGT applies the GT predicate on the "per_tx_cap_sats" field.
func PerTxCapSatsGT(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGT(FieldPerTxCapSats, v))
}

// PerTxCapSatsGTE applies the GTE predicate on the "per_tx_cap_sats" field.
func PerTxCapSatsGTE(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGTE(FieldPerTxCapSats, v))
}

// PerTxCapSatsLT applies the LT predicate on the "per_tx_cap_sats" field.
func PerTxCapSatsLT(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLT(FieldPerTxCapSats, v))
}

// PerTxCapSatsLTE applies the LTE predicate on the "per_tx_cap_sats" field.
func PerTxCapSatsLTE(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLTE(FieldPerTxCapSats, v))
}

// RollingLimitSatsEQ applies the EQ predicate on the "rolling_limit_sats" field.
func RollingLimitSatsEQ(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldRollingLimitSats, v))
}

// RollingLimitSatsNEQ applies the NEQ predicate on the "rolling_limit_sats" field.
func RollingLimitSatsNEQ(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNEQ(FieldRollingLimitSats, v))
}

// RollingLimitSatsIn applies the In predicate on the "rolling_limit_sats" field.
func RollingLimitSatsIn(vs ...uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldIn(FieldRollingLimitSats, vs...))
}

// RollingLimitSatsNotIn applies the NotIn predicate on the "rolling_limit_sats" field.
func RollingLimitSatsNotIn(vs ...uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNotIn(FieldRollingLimitSats, vs...))
}

// RollingLimitSatsGT applies the GT predicate on the "rolling_limit_sats" field.
func RollingLimitSatsGT(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGT(FieldRollingLimitSats, v))
}

// RollingLimitSatsGTE applies the GTE predicate on the "rolling_limit_sats" field.
func RollingLimitSatsGTE(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGTE(FieldRollingLimitSats, v))
}

// RollingLimitSatsLT applies the LT predicate on the "rolling_limit_sats" field.
func RollingLimitSatsLT(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLT(FieldRollingLimitSats, v))
}

// RollingLimitSatsLTE applies the LTE predicate on the "rolling_limit_sats" field.
func RollingLimitSatsLTE(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLTE(FieldRollingLimitSats, v))
}

// RollingWindowSecondsEQ applies the EQ predicate on the "rolling_window_seconds" field.
func RollingWindowSecondsEQ(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldRollingWindowSeconds, v))
}

// RollingWindowSecondsNEQ applies the NEQ predicate on the "rolling_window_seconds" field.
func RollingWindowSecondsNEQ(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNEQ(FieldRollingWindowSeconds, v))
}

// RollingWindowSecondsIn applies the In predicate on the "rolling_window_seconds" field.
func RollingWindowSecondsIn(vs ...uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldIn(FieldRollingWindowSeconds, vs...))
}

// RollingWindowSecondsNotIn applies the NotIn predicate on the "rolling_window_seconds" field.
func RollingWindowSecondsNotIn(vs ...uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNotIn(FieldRollingWindowSeconds, vs...))
}

// RollingWindowSecondsGT applies the GT predicate on the "rolling_window_seconds" field.
func RollingWindowSecondsGT(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGT(FieldRollingWindowSeconds, v))
}

// RollingWindowSecondsGTE applies the GTE predicate on the "rolling_window_seconds" field.
func RollingWindowSecondsGTE(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGTE(FieldRollingWindowSeconds, v))
}

// RollingWindowSecondsLT applies the LT predicate on the "rolling_window_seconds" field.
func RollingWindowSecondsLT(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLT(FieldRollingWindowSeconds, v))
}

// RollingWindowSecondsLTE applies the LTE predicate on the "rolling_window_seconds" field.
func RollingWindowSecondsLTE(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLTE(FieldRollingWindowSeconds, v))
}

// PerTxUnlimitedEQ applies the EQ predicate on the "per_tx_unlimited" field.
func PerTxUnlimitedEQ(v bool) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldPerTxUnlimited, v))
}

// PerTxUnlimitedNEQ applies the NEQ predicate on the "per_tx_unlimited" field.
func PerTxUnlimitedNEQ(v bool) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNEQ(FieldPerTxUnlimited, v))
}

// RollingUnlimitedEQ applies the EQ predicate on the "rolling_unlimited" field.
func RollingUnlimitedEQ(v bool) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldRollingUnlimited, v))
}

// RollingUnlimitedNEQ applies the NEQ predicate on the "rolling_unlimited" field.
func RollingUnlimitedNEQ(v bool) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNEQ(FieldRollingUnlimited, v))
}

// SpentSatsEQ applies the EQ predicate on the "spent_sats" field.
func SpentSatsEQ(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldSpentSats, v))
}

// SpentSatsNEQ applies the NEQ predicate on the "spent_sats" field.
func SpentSatsNEQ(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNEQ(FieldSpentSats, v))
}

// SpentSatsIn applies the In predicate on the "spent_sats" field.
func SpentSatsIn(vs ...uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldIn(FieldSpentSats, vs...))
}

// SpentSatsNotIn applies the NotIn predicate on the "spent_sats" field.
func SpentSatsNotIn(vs ...uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNotIn(FieldSpentSats, vs...))
}

// SpentSatsGT applies the GT predicate on the "spent_sats" field.
func SpentSatsGT(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGT(FieldSpentSats, v))
}

// SpentSatsGTE applies the GTE predicate on the "spent_sats" field.
func SpentSatsGTE(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGTE(FieldSpentSats, v))
}

// SpentSatsLT applies the LT predicate on the "spent_sats" field.
func SpentSatsLT(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLT(FieldSpentSats, v))
}

// SpentSatsLTE applies the LTE predicate on the "spent_sats" field.
func SpentSatsLTE(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLTE(FieldSpentSats, v))
}

// WindowStartEQ applies the EQ predicate on the "window_start" field.
func WindowStartEQ(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldWindowStart, v))
}

// WindowStartNEQ applies the NEQ predicate on the "window_start" field.
func WindowStartNEQ(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNEQ(FieldWindowStart, v))
}

// WindowStartIn applies the In predicate on the "window_start" field.
func WindowStartIn(vs ...time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldIn(FieldWindowStart, vs...))
}

// WindowStartNotIn applies the NotIn predicate on the "window_start" field.
func WindowStartNotIn(vs ...time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNotIn(FieldWindowStart, vs...))
}

// WindowStartGT applies the GT predicate on the "window_start" field.
func WindowStartGT(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGT(FieldWindowStart, v))
}

// WindowStartGTE applies the GTE predicate on the "window_start" field.
func WindowStartGTE(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGTE(FieldWindowStart, v))
}

// WindowStartLT applies the LT predicate on the "window_start" field.
func WindowStartLT(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLT(FieldWindowStart, v))
}

// WindowStartLTE applies the LTE predicate on the "window_start" field.
func WindowStartLTE(v time.Time) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLTE(FieldWindowStart, v))
}

// WindowStartIsNil applies the IsNil predicate on the "window_start" field.
func WindowStartIsNil() predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldIsNull(FieldWindowStart))
}

// WindowStartNotNil applies the NotNil predicate on the "window_start" field.
func WindowStartNotNil() predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNotNull(FieldWindowStart))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v uint64) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLTE(FieldVersion, v))
}

// OwnerSignatureEQ applies the EQ predicate on the "owner_signature" field.
func OwnerSignatureEQ(v []byte) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldEQ(FieldOwnerSignature, v))
}

// OwnerSignatureNEQ applies the NEQ predicate on the "owner_signature" field.
func OwnerSignatureNEQ(v []byte) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNEQ(FieldOwnerSignature, v))
}

// OwnerSignatureIn applies the In predicate on the "owner_signature" field.
func OwnerSignatureIn(vs ...[]byte) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldIn(FieldOwnerSignature, vs...))
}

// OwnerSignatureNotIn applies the NotIn predicate on the "owner_signature" field.
func OwnerSignatureNotIn(vs ...[]byte) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldNotIn(FieldOwnerSignature, vs...))
}

// OwnerSignatureGT applies the GT predicate on the "owner_signature" field.
func OwnerSignatureGT(v []byte) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGT(FieldOwnerSignature, v))
}

// OwnerSignatureGTE applies the GTE predicate on the "owner_signature" field.
func OwnerSignatureGTE(v []byte) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldGTE(FieldOwnerSignature, v))
}

// OwnerSignatureLT applies the LT predicate on the "owner_signature" field.
func OwnerSignatureLT(v []byte) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLT(FieldOwnerSignature, v))
}

// OwnerSignatureLTE applies the LTE predicate on the "owner_signature" field.
func OwnerSignatureLTE(v []byte) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.FieldLTE(FieldOwnerSignature, v))
}

// HasDelegationGrant applies the HasEdge predicate on the "delegation_grant" edge.
func HasDelegationGrant() predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DelegationGrantTable, DelegationGrantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDelegationGrantWith applies the HasEdge predicate on the "delegation_grant" edge with a given conditions (other predicates).
func HasDelegationGrantWith(preds ...predicate.DelegationGrant) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(func(s *sql.Selector) {
		step := newDelegationGrantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DelegationGrantSpender) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DelegationGrantSpender) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DelegationGrantSpender) predicate.DelegationGrantSpender {
	return predicate.DelegationGrantSpender(sql.NotPredicates(p))
}
